### ISSUE TITLE
Ver 0.4.0 Unable to load DLL 'onnxruntime-genai' or one of its dependencies: The specified module could not be found. (0x8007007E)'

### ISSUE THREAD

**Issue by strikene** [microsoft/onnxruntime-genai#1004]
I have installed CUDA11.8, as well as cudnn-windows-x86_64-8.9.6.50_cuda11
I can use 0.3.0 to load Phi3mini(Phi-3-mini-4k-instruct-onnx\cuda\cuda-int4-awq-block-128)

As soon as I upgrade to 0.4.0, an exception is thrown
Unable to load DLL 'onnxruntime-genai' or one of its dependencies: The specified module could not be found. (0x8007007E)'

VS2022 17.11.5
Windows 11 23H2 22631.4169
Consolapp with .NET 8
Package Microsoft.ML.OnnxRuntimeGenAI.Cuda Version="0.4.0"

**Comment by strikene** [comment]
- [ ]

**Comment by SwamyNallamalli** [comment]
Hello, how did you get this resolved?

**Comment by natke** [comment]
What version of Microsoft.ML.OnnxRuntimeGenAI?

**Comment by SwamyNallamalli** [comment]
I am using 0.6.0. 
I added Microsoft.ML.OnnxRunTimeGenAI (0.6.0) to my project and the project is building fine. its the run time error:
Code:
```
var ogaHandle = new OgaHandle();
var config = new Config(modelPath);
```
Exception:
```
Unable to load DLL 'onnxruntime-genai' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Microsoft.ML.OnnxRuntimeGenAI.NativeMethods.OgaCreateConfig(Byte[] configPath, IntPtr& config)
   at Microsoft.ML.OnnxRuntimeGenAI.Config..ctor(String modelPath)
```

**Comment by SwamyNallamalli** [comment]
> What version of Microsoft.ML.OnnxRuntimeGenAI? Can you update to 0.6.0?

I tried 0.6.0 and now tried with 0.7.0 too. The issue is same.
Is there any other package I need to refer to for getting onnxruntime-genai

**Comment by SwamyNallamalli** [comment]
> [@SwamyNallamalli](https://github.com/SwamyNallamalli) just making sure that you have a dependency on [`Microsoft.ML.OnnxRuntimeGenAI`](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI) and not directly on [`Microsoft.ML.OnnxRuntimeGenAI.Managed`](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI.Managed).
> 
> The latter won't work out of the box. But if you take a dependency on the former, it should work.

I did try taking dependency on Microsoft.ML.OnnxRuntimeGenAI alone:
     `<PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" Version="0.7.0" />`

But in bin/debug folder I don't see onnxruntime-genai.dll file.

I only see the following files related to onnxruntime:
```
Microsoft.ML.OnnxRuntime.dll
Microsoft.ML.OnnxRuntimeGenAI.dll
onnxruntime.dll
onnxruntime_providers_shared.dll
```
The error is still the same:
   ```
at Microsoft.ML.OnnxRuntimeGenAI.NativeMethods.OgaShutdown()
   at Microsoft.ML.OnnxRuntimeGenAI.OgaHandle.Dispose(Boolean disposing)
   at Microsoft.ML.OnnxRuntimeGenAI.OgaHandle.Dispose()
```
