### ISSUE TITLE
OuteAI support 

### ISSUE THREAD

**Issue by janjanusek** [microsoft/onnxruntime-genai#1033]
https://huggingface.co/OuteAI/OuteTTS-0.1-350M

Is it possible to use gennai for this model? it's llama3 based but slightly different 🤷🏼‍♂️ ca we add support?

**Comment by kunal-vaishnavi** [comment]
The [architecture](https://huggingface.co/OuteAI/OuteTTS-0.1-350M/blob/5038e9f232fe74ce51cd1c1c111467640bfdc86d/config.json#L4) is `LlamaForCausalLM` and that is supported by the model builder. You can use the model builder to get the ONNX model and [run the generation loop](https://github.com/edwko/OuteTTS/blob/e8614bc4772538ee34cb5e4dedab3349b377d02f/outetts/v0_1/interface.py#L92) with ONNX Runtime GenAI.

The [CTC alignment](https://github.com/edwko/OuteTTS/blob/e8614bc4772538ee34cb5e4dedab3349b377d02f/outetts/v0_1/interface.py#L53) for the output tokens would have to be done outside of ONNX Runtime GenAI as the support is not currently there. If you run into any ONNX Runtime GenAI tokenizer issues with `OuteTTS`, you can add them here and use Hugging Face's tokenizer instead. Please feel free to open a PR to contribute as well.
