### ISSUE TITLE
Session option for enable_mem_pattern looks at incorrect value

### ISSUE THREAD

**Issue by namalr** [microsoft/onnxruntime-genai#1046]
https://github.com/microsoft/onnxruntime-genai/blob/dc9bc02cea45895560332a89547c7400d18ac4a0/src/models/model.cpp#L343-L348

Currently `enable_cpu_mem_arena.value()`  is tested when it should be `enable_mem_pattern.value()`.

**Comment by RyanUnderhill** [comment]
Good catch, will fix this asap.

PR Created: https://github.com/microsoft/onnxruntime-genai/pull/1047

**Comment by RyanUnderhill** [comment]
Fix is in, will be in the next release
