### ISSUE TITLE
Error loading Phi-3-Vision ONNX CPU Model

### ISSUE THREAD

**Issue by inaraghi** [microsoft/onnxruntime-genai#1055]
**Describe the bug**

Error loading Phi-3-Vision ONNX CPU Model  : 

''' 
import onnxruntime_genai as og
model = og.Model(model_path) 
'''

Error encountered while parsing './cpu-int4-rtn-block-32-acc-level-4\genai_config.json' 
JSON Error: Unknown value: visual_features

**To Reproduce**
1. Download the model (from HuggingFace)
2. Follow steps described here : https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html#run-on-cpu

**Expected behavior**
Model successfully loaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - CPU : Intel i7
 - 16 Go Memory

**Comment by skyline75489** [comment]
Hi @inaraghi. This is a known issue due to the structural changes in the model & code. Are you using the 0.5.0 version of GenAI?

@kunal-vaishnavi do we have the newer model released yet? Or should we suggest using an old version?

**Comment by kunal-vaishnavi** [comment]
The new models are ready but we are awaiting final internal approval before releasing them on Hugging Face this week. Downgrading to an older version of ONNX Runtime GenAI is recommended until then.

**Comment by inaraghi** [comment]
Thank you very much for your prompt response. Downgrading to onnxruntime-genai 0.4.0 successfully resolved the issue.
I'll try the latest version once the new models are released. Thank you.

**Comment by kunal-vaishnavi** [comment]
The new [Phi-3 vision](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx) and [Phi-3.5 vision](https://huggingface.co/microsoft/Phi-3.5-vision-instruct-onnx) ONNX models have now been released.

**Comment by azchohfi** [comment]
I don't see new versions. I just redownloaded it and it is still failing.
