### ISSUE TITLE
Can't install version 0.50 using pip (python 3.8)

### ISSUE THREAD

**Issue by elephantpanda** [microsoft/onnxruntime-genai#1072]
I do
`pip install --pre onnxruntime-genai`
or
`pip install --pre onnxruntime-genai-directml`

and it just reinstalls version 0.40.

I am using Windows 11. Python 3.8

**Comment by kunal-vaishnavi** [comment]
You can remove the `--pre` portion in your install command. The `--pre` is only needed for when release candidates are published. Stable releases can be installed without `--pre`.

**Comment by kunal-vaishnavi** [comment]
You can remove the `--pre` portion in your install command. The `--pre` is only needed for when release candidates are published. Stable releases can be installed without `--pre`. [To align with ONNX Runtime](https://github.com/microsoft/onnxruntime/releases/tag/v1.20.0), Python 3.8 and Python 3.9 have also been deprecated so new wheels have been published for Python 3.10 or newer.

**Comment by elephantpanda** [comment]
OK, so I got to upgrade my python I guess. 😔

A bit annoying cos every time I update my python it breaks something else which doesn't work with the latest python. 

Oh. Well. Worse things have happened.

**Comment by skyline75489** [comment]
ORT itself drops support for Python 3.8 & 3.9 in 1.20 release, so must we. Sorry about it.
