### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by r4ghu** [microsoft/onnxruntime-genai#1076]
Hi OnnxRuntime GenAI,
First of all thank you for creating this easy to use & high performance library for LLMs. I am currently working on WebGPU related optimizations and would surely benefit if OnnxRuntime GenAI supports WebGPU supported node packages for easier integration. I have seen couple of PRs related to WebGPU execution provider, but I haven't come across any documentation on how to utilize it. 

I would like to know if there is any early-access or pre-release version where I can test WebGPU execution provider. If not, I would like to know the timeline in which I can start using this EP.

**Comment by guschmue** [comment]
We do have a plan to release webgpu/native ep, next onnxruntime release.
Currently we have the ops needed for llm's but before we release it we want to add support for all webgpu ops supported by onnxruntime-web so to avoid confusion of what models will work.

You can build onnxruntime/main with --use_webgpu, works on windows, macos and linux. 
After this all you need it to request WebGpuExecutionProvider as execution provider.

genai is does support webgpu on main as well with --use_webgpu. When using with genai, we currently need the models generated with '-e web' (when using model builder, gqa is still having some issue with webgpu/native) and in genai_config.json you need to change 'web' to 'webgpu' once the model is generated.
gqa support should be coming soon.
