### ISSUE TITLE
Add how to build from source for Android (and iOS)

### ISSUE THREAD

**Issue by Agredo** [microsoft/onnxruntime-genai#1081]
I am developing with genai an .NET MAUI App. Now I would like to bring this app on Android but getiing error: 
![Image](https://github.com/user-attachments/assets/66b24d24-393b-4080-acde-ca4605832d8c)

I followed the build from source instruction from here https://onnxruntime.ai/docs/genai/howto/build-from-source.html and dowloaded the android packages. 

But trying to buil by using the dot net build commands from here: https://github.com/microsoft/onnxruntime-genai/pull/923/files#diff-e86543a0294e755b065e28bb918be89e0e76957f3bb45725f351fd69bee7663f

failed: 
![Image](https://github.com/user-attachments/assets/27148af5-0c5b-4535-91da-f596f0b297e5)

Maybe someone can help me. 

Thanks

**Comment by skyline75489** [comment]
Hi @Agredo . We've just released [0.5.1](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI/0.5.1) and it should have iOS & Android support in the NuGet package. Feel free to try it out

**Comment by skyline75489** [comment]
@Agredo Are you using MAUI? Could you provide us with more information about your environment? Like the target android version, target android ABI, etc.

**Comment by Agredo** [comment]
Here is a sample project. @skyline75489 
[Nexile.zip](https://github.com/user-attachments/files/17841420/Nexile.zip)

**Comment by skyline75489** [comment]
I see you're using the `Microsoft.ML.OnnxRuntimeGenAI.DirectML` package, which is a Windows-only package, because DirectML is Windows only. Try [Microsoft.ML.OnnxRuntimeGenAI](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI) instead.

**Comment by skyline75489** [comment]
DirectML itself probably will never be compatible with Android & iOS. But we do have the plan to add more EP support, such as CoreML and WebGPU in the future, which should utilize GPU/NPU on mobile platforms.

**Comment by Agredo** [comment]
Thank you very much. This sound very promising!
