### ISSUE TITLE
Images.open_bytes doesn't exist

### ISSUE THREAD

**Issue by alsmeirelles** [microsoft/onnxruntime-genai#1099]
The Images class defined in python bindings suggests the existence of a open_bytes static methoda that in teory could return an object accepted as the "images" parameter of the multimodal processor. The bindings definition:

```c++
pybind11::class_<Images>(m, "Images")
      .def_static("open", [](pybind11::args image_paths) {
        if (image_paths.empty())
          throw std::runtime_error("No images provided");

        std::vector<std::string> image_paths_string;
        std::vector<const char*> image_paths_vector;
        for (auto image_path : image_paths) {
          if (!pybind11::isinstance<pybind11::str>(image_path))
            throw std::runtime_error("Image paths must be strings.");
          image_paths_string.push_back(image_path.cast<std::string>());
          image_paths_vector.push_back(image_paths_string.back().c_str());
        }

        return LoadImages(image_paths_vector);
      })
      .def_static("open_bytes", [](pybind11::args image_datas) {
        if (image_datas.empty())
          throw std::runtime_error("No images provided");

        std::unique_ptr<ort_extensions::ImageRawData[]> image_raw_data = std::make_unique<ort_extensions::ImageRawData[]>(image_datas.size());
        for (size_t i = 0; i < image_datas.size(); ++i) {
          if (!pybind11::isinstance<pybind11::bytes>(image_datas[i]))
            throw std::runtime_error("Image data must be bytes.");
          auto bytes = image_datas[i].cast<pybind11::bytes>();
          pybind11::buffer_info info(pybind11::buffer(bytes).request());
          uint8_t* data = reinterpret_cast<uint8_t*>(info.ptr);
          image_raw_data[i] = ort_extensions::ImageRawData(data, data + info.size);
        }

        return std::make_unique<Images>(std::move(image_raw_data), image_datas.size());
      });
``` 
Despite that, when I try to call the open_bytes method by passing a byte sequence from a numpy array I get the error:

AttributeError: type object 'onnxruntime_genai.onnxruntime_genai.Images' has no attribute 'open_bytes'

Indeed, help(onnxruntime_genai.Images) does not show open_bytes as a method, only open, which only accepts file paths as input. 

So, is there something wrong with the python bindings? Or the way to pass a ndarray to the multimodal processor should be through a different method? I really don't want to save the image to file to be read again using Images.open.

Thanks in advance for the attention

**Comment by baijumeswani** [comment]
What version of onnxruntime-genai are you using? Are you building from source or using > 0.5.0?

**Comment by baijumeswani** [comment]
Here is a sample on how the functionality can be used: https://github.com/microsoft/onnxruntime-genai/blob/e27e2b577dba7da8d2c7da247f5692685cc41ffe/test/python/test_onnxruntime_genai_api.py#L464-L481

**Comment by alsmeirelles** [comment]
> What version of onnxruntime-genai are you using? Are you building from source or using >= 0.5.0?

Sorry for the late reply @baijumeswani. I was using onnxruntime-genai-cuda-0.4.0 installed from Pypi. Upgrading to 0.5.2 solved the issue of the open_bytes being unavailable.

Thanks for helping
