### ISSUE TITLE
Can't seem to create a onnxruntime_genai.Tokenizer when using llama3 8b

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [microsoft/onnxruntime-genai#1100]
Steps to prepare model:
```
python -m venv my_env
source my_env/bin/activate
pip install torch transformers onnx onnxruntime
pip install --pre onnxruntime-genai

python3 -m onnxruntime_genai.models.builder -m meta-llama/Meta-Llama-3-8B-Instruct -o llama3_onnx -p int4 -e cpu -c cache
```

Given the following python code:

```
import onnxruntime_genai as og

model = og.Model('llama3_onnx')
tokenizer = og.Tokenizer(model)
```

I get this RuntimeError:
```
>>> tokenizer = og.Tokenizer(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [json.exception.type_error.302] type must be string, but is array
```

I'm not too sure what I am doing wrong -- can someone help? I'm very new to the framework, so perhaps I misunderstood something -- e.g. am I supposed to run something extra to prepare tokenizer?

**Comment by kunal-vaishnavi** [comment]
This is a known issue with Hugging Face's `transformers` package. Suggested workarounds can be found [here](https://github.com/microsoft/onnxruntime-genai/issues/991#issuecomment-2420760445).

Also, you can install the latest stable version of ONNX Runtime GenAI with `pip install onnxruntime-genai`. The `--pre` only needs to be added if you want to install release candidate packages that are published before a stable release.
