### ISSUE TITLE
`pip install onnxruntime-genai` does not work

### ISSUE THREAD

**Issue by xquyvu** [microsoft/onnxruntime-genai#1102]
**Describe the bug**

Cannot install the package. Got the following error message:

```text
ERROR: Could not find a version that satisfies the requirement onnxruntime-genai (from versions: none)
ERROR: No matching distribution found for onnxruntime-genai
```

I'm aware of this open issue: https://github.com/microsoft/onnxruntime-genai/issues/559, but it's not fully resolved.

**To Reproduce**

`pip install onnxruntime-genai`
or
`pip install onnxruntime-genai --pre`

**Expected behavior**
The package installs without issue

**Desktop (please complete the following information):**
```python
>>> import platform
>>> print(platform.machine())
aarch64
>>> print(platform.version())
#1 SMP Wed Oct  2 16:38:00 UTC 2024
>>> print(platform.platform())
Linux-6.10.4-linuxkit-aarch64-with-glibc2.35
>>> print(platform.system())
Linux
>>> print(platform.processor())
aarch64
```

Python version: `3.12.7`

**Additional context**

**Comment by xquyvu** [comment]
But works when running on an AML compute instance
```python
>>> import platform
>>> print(platform.machine())
x86_64
>>> print(platform.version())
#82~20.04.1-Ubuntu SMP Tue Sep 3 12:27:43 UTC 2024
>>> print(platform.platform())
Linux-5.15.0-1073-azure-x86_64-with-glibc2.31
>>> print(platform.system())
Linux
>>> print(platform.processor())
x86_64
```

Python version: `3.12.2`

**Comment by maulberto3** [comment]
I believe this is happening starting with version 0.5.2 uploaded to pypi Nov 25. Because I just downloaded it a few days ago and everything went fine.

**Comment by baijumeswani** [comment]
Python whls for linux aarch64 are not published. You would need to build the whl from source for linux aarch64.

We can look into adding this for an upcoming release.
