### ISSUE TITLE
Running benchmark_e2e.py with phi-3.5-mini-4k-instruct causes "AttributeError: 'onnxruntime_genai.onnxruntime_genai.GeneratorParams' object has no attribute 'input_ids'""

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime-genai#1108]
**Describe the bug**

**To Reproduce**
1. build onnxruntime and onnxruntim-genai from source. Install both packages
2. python -m onnxruntime_genai.models.builder -m microsoft/Phi-3.5-mini-instruct -e cpu -p int4 --extra_options int4_accuracy_level=4 int4_block_size=32 -o C:/example-models/Phi-3.5/phi-3.5-mini-4k-instruct-int4-int8-blklen32-cpu
3. python benchmark_e2e.py -l 128 -g 4 -i C:\example-models\Phi-3.5\phi-3.5-mini-4k-instruct-int4-int8-blklen32-cpu

**Expected behavior**
run the model and outputs perf data.

**Screenshots**
(onnx) c:\LiqunWA\onnxruntime-genai\benchmark\python>python benchmark_e2e.py -l 128 -g 4 -i C:\LiqunWA\example-models\Phi-3.5\phi-3.5-mini-4k-instruct-int4-int8-blklen32-cpu

Args: batch_size = 1, prompt_length = 128, tokens = 4, max_length = 132
Traceback (most recent call last):
  File "c:\LiqunWA\onnxruntime-genai\benchmark\python\benchmark_e2e.py", line 426, in <module>
    main(args)
  File "c:\LiqunWA\onnxruntime-genai\benchmark\python\benchmark_e2e.py", line 385, in main
    metrics = run_benchmark(args, batch_size, prompt_length, gen_length, max_length)
  File "c:\LiqunWA\onnxruntime-genai\benchmark\python\benchmark_e2e.py", line 236, in run_benchmark
    prompt = [generate_prompt(model, tokenizer, prompt_length, args.use_graph_capture)] * batch_size
  File "c:\LiqunWA\onnxruntime-genai\benchmark\python\benchmark_e2e.py", line 75, in generate_prompt
    params.input_ids = tokens
AttributeError: 'onnxruntime_genai.onnxruntime_genai.GeneratorParams' object has no attribute 'input_ids'

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22]  onnxruntime main branch onh Nov 11/30, 2024, onnxruntime_genai main on Nov 25th, 2024

**Additional context**

**Comment by skyline75489** [comment]
The `input_ids` in `GeneratorParams` was removed in https://github.com/microsoft/onnxruntime-genai/commit/7c0f0d198be29ede421ce29beac8e1c28139510c#diff-e5c654a3aa3921dc2a0e849a182bbccae2051eab0a7580000faa8e4013c48fd4L398 . I guess the `benchmark_e2e.py` script needs to be updated to reflect this change.
