### ISSUE TITLE
Phi3.5-mini fails to execute using phi3-qa.py

### ISSUE THREAD

**Issue by suyash-narain** [microsoft/onnxruntime-genai#1133]
On executing phi3-qa.py using the latest commits on this script, execution of phi3.5-mini model fails.
I get the error:

> $python3 phi3-qa.py -m cpu_and_mobile/cpu-int4-rtn=block-32-acc-level-4
> Input: Hello, how are you?
> Traceback (most recent call last):
>     File "/home/user/phi3-qa.py", line 92, in <module> main(args)
>     File "/home/user/phi3-qa.py", line 42, in main
>     generator = og.Generator(model,params)
> RuntimeError: input_ids not set in GeneratorParams

if i revert this change _'generator.append_tokens(input_tokens)'_ with _params.input_ids = input_tokens_ and _generator.compute_logits()_, it works without any issues.

I am using Ubuntu 22.04 with ort v1.20.1 and gen-ai v0.5.2

**Comment by kunal-vaishnavi** [comment]
You can see [this announcement](https://github.com/microsoft/onnxruntime-genai/issues/1142) for more information on which example script to use.
