### ISSUE TITLE
Support for T5 and java support

### ISSUE THREAD

**Issue by balachandarsv** [microsoft/onnxruntime-genai#152]
https://github.com/microsoft/onnxruntime/issues/19718

Can someone let me know if this can be supported in genai? 

Thank you

**Comment by RyanUnderhill** [comment]
Yes, support for T5 is on our roadmap. We don't have a timeline for it yet.

Java is not yet on the roadmap, but nothing is impossible if it's what people want.

**Comment by balachandarsv** [comment]
Thank you for responding. Java APIs would be of great help.

**Comment by natke** [comment]
Java is on the roadmap as part of our support for mobile/android in the May timeframe.

**Comment by balachandarsv** [comment]
Thank you. Hoping it would support Java in Desktops/Server and not only on mobile devices.

**Comment by natke** [comment]
Oh yes, apologies that wasn't clear. It will support Java on desktop and server as well as mobile. It's just that mobile is our primary driver for Java bindings
