### ISSUE TITLE
Support onnxruntime on device. 

### ISSUE THREAD

**Issue by blayer** [microsoft/onnxruntime-genai#195]
Hi team, 
I wonder if onnxruntime-genai has the mobile support in horizon. Google/TF recently released a [GAI support on device](https://developers.googleblog.com/2024/03/running-large-language-models-on-device-with-mediapipe-andtensorflow-lite.html). 
Thanks.

**Comment by natke** [comment]
Hi @blayer, yes, we will have support for on device in the May timeframe.

**Comment by blayer** [comment]
@natke great! Thanks for sharing this.
