### ISSUE TITLE
Host ONNX models

### ISSUE THREAD

**Issue by stephentoub** [microsoft/onnxruntime-genai#218]
With how the project is currently configured, everyone needs to use python to convert models to ONNX, even when just wanting to experiment / try it out and using a different language. It'd be better if some canned onnx models / config files were hosted somewhere such that the getting started experience was just download and F5.

**Comment by natke** [comment]
Hi @stephentoub, we agree with you! We are working through the necessary compliance and regulatory steps to do this

**Comment by ramkrishna2910** [comment]
@natke Can we host these onnx models in the ONNX Model Zoo?
I can help with that.

**Comment by natke** [comment]
@stephentoub We have started the upload process with Phi-3 being here: 

https://huggingface.co/microsoft/Phi-3-mini-4k-instruct
https://huggingface.co/microsoft/Phi-3-mini-128k-instruct

More to come!

**Comment by natke** [comment]
@ramkrishna2910, @MaanavD will coordinate with you on hosting in the ONNX model zoo

**Comment by stephentoub** [comment]
> We have started the upload process

Excellent, thanks.

**Comment by stephentoub** [comment]
Hmm, where should I be looking? I don't see any .onnx files for either of those models on HF.

**Comment by kunal-vaishnavi** [comment]
The Phi-3 mini 4K ONNX models are available [here](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx) and the Phi-3 mini 128K ONNX models are available [here](https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx).

**Comment by natke** [comment]
> > https://huggingface.co/microsoft/Phi-3-mini-4k-instruct
> > https://huggingface.co/microsoft/Phi-3-mini-128k-instruct
> 
> Hmm, where should I be looking? I don't see any .onnx files for either of those models on HF.

My apologies. I had linked to the base models. Please see corrected links here: https://github.com/microsoft/onnxruntime-genai/issues/218#issuecomment-2091945737

**Comment by natke** [comment]
Closing this issue. We will announce new models as they become available
