### ISSUE TITLE
Can Not Install the Python package

### ISSUE THREAD

**Issue by fydeos-alex** [microsoft/onnxruntime-genai#224]
there was something wrong when I ran this install code from the docs:
```
pip install numpy
pip install onnxruntime-genai --pre --index-url=
https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/`

```

The code didn't work either on Linux ARM64 or my MBA M1. Is there anything wrong with this package link?

**Comment by baijumeswani** [comment]
> The code didn't work either on Linux ARM64 or my MBA M1. Is there anything wrong with this package link?

As far as I know, we have not published mac OS and arm64 wheels yet which might be the reason you're seeing the error. cc @jchen35

**Comment by fydeos-alex** [comment]
Thank you. I installed it on my x86 Linux and it worked. I am waiting for your support for other platforms. I will close this issue.
