### ISSUE TITLE
phi2

### ISSUE THREAD

**Issue by frankzhao112** [microsoft/onnxruntime-genai#237]
hello,sir 
thank u for you great work. I successfully convert and quantize mircrosft phi-2 to phi-2 ort, and inference sucessfully.
![image](https://github.com/microsoft/onnxruntime-genai/assets/128885107/374335d1-e4bd-4614-8aec-9a77c71e3dc1)
but when I use the phi2 model that I trained from 0 , the bug happens. Because I want to minimize the size of phi2, I change the phi hidden size from 2560 to 768,   change the number of the attention heads from 32 to 12,    and minimize  the intermediate_size to 4096.
![image](https://github.com/microsoft/onnxruntime-genai/assets/128885107/0c2977fa-05e7-4564-b143-600af64a511e)
and then, I get the bug when inference . but I don't know how correct  cos_cache dimension in onnxruntime-genai framework. So, could u give me some ideas about how to fix the bug.

**Comment by natke** [comment]
Thank you for the feedback @frankzhao112. We will look into this issue.

**Comment by kunal-vaishnavi** [comment]
Did you create the ONNX model using the model builder? If so, can you create the ONNX model again using the changes from the linked PR?
