### ISSUE TITLE
Wheel file name does not get updated for new versions

### ISSUE THREAD

**Issue by natke** [microsoft/onnxruntime-genai#275]
If I build from source without deleting the build folder, the version name in the wheel does not get updated. Whilst the workaround is to delete the build folder, this is confusing and could cause errors.

**Comment by baijumeswani** [comment]
This happens because we [cache the version info at the time of build](https://github.com/microsoft/onnxruntime-genai/blob/cf18f30961740089bb8f1da9c228d2ca8d17023b/CMakeLists.txt#L13). We can avoid caching and probably this error might go away.
