### ISSUE TITLE
Phi-3 on mobile

### ISSUE THREAD

**Issue by cvb941** [microsoft/onnxruntime-genai#316]
Hi, is there a guide on how to to use the Phi-3 ONNX models (https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx) on mobile (iOS + Android)?

Do I understand correctly, that the raw model needs to be preprocessed first? The [guide](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi-3-tutorial.md) mentions using [model-qa.py](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/model-qa.py), which seems to do the preprocessing behind the scenes using the new Generate() API, but the script only outputs the inference.
Is there a way to also export the preprocessed model, to use in ONNX runtime on mobile?

**Comment by natke** [comment]
@cvb941 We have a sample here that uses the C API temporarily while we work on Java and Objective-C bindings. PR should be merged very soon https://github.com/microsoft/onnxruntime-inference-examples/pull/420

**Comment by natke** [comment]
And to answer your question about pre processing, yes the generate() API takes care of pre processing. You do not need to add the code for this in you application

**Comment by natke** [comment]
Closing as inactive. Please re-open or let us know of your progress!
