### ISSUE TITLE
.NET Microsoft.ML.OnnxRuntimeGenAI 0.1.0-rc4 fails loading `Phi-3-mini-4k-instruct-onnx`

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime-genai#318]
This:
```csharp
using Microsoft.ML.OnnxRuntimeGenAI;
var modelDirectory = args.Length == 1 ? args[0] :
    @"C:\git\oss\Phi-3-mini-4k-instruct-onnx\cuda\cuda-int4-rtn-block-32";
var model = new Model(modelDirectory);
```
Will fail with:
```
Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: 
'Error encountered while parsing 'C:\git\oss\Phi-3-mini-4k-instruct-onnx\cuda\cuda-fp16\genai_config.json' 
JSON Error: Unknown value: eos_token_id at line 34 index 27'
```
and at that line json looks like
```
        "eos_token_id": [
            32000,
            32007
        ],
```
so on could guess loading does not support array here?

**Comment by baijumeswani** [comment]
Could you share the version of the nuget package you're using. Please try to use the pre-release candidate `0.2.0-rc3` version which has the necessary support for running the phi-3 model.

https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI.Managed/0.2.0-rc3

**Comment by nietras** [comment]
Version shown in title. Used latest from private feed... will try to look for 0.2.0...

**Comment by nietras** [comment]
Documentation says to use https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/nuget/v3/index.json as feed but this does not have latest so seems like this has been switched to official nuget feed which is why I didn't get latest. Perhaps update documentation :)

Model now instantiates with some warnings though:
```
2024-04-25 11:20:18.0715013 [W:onnxruntime:onnxruntime-genai, session_state.cc:1166 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-04-25 11:20:18.0793099 [W:onnxruntime:onnxruntime-genai, session_state.cc:1168 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
```
