### ISSUE TITLE
Error loading the assembly file 

### ISSUE THREAD

**Issue by PrestigeDevop** [microsoft/onnxruntime-genai#358]
Hello , I've installed and used the library with python , however , the .net example and dlls seems have some issues 

![image](https://github.com/microsoft/onnxruntime-genai/assets/85388342/856ce95e-44d6-4343-8964-2cdb2da95696)

![image](https://github.com/microsoft/onnxruntime-genai/assets/85388342/14dd4d73-c79e-47dd-b6f6-4833d374c3ab)

I've already added Nuget packages  but it seems it doesn't support my system ? 

intel 64 
win11pro 

![image](https://github.com/microsoft/onnxruntime-genai/assets/85388342/6aed5814-96b4-4c7d-8538-1d7599ab2075)

**Comment by baijumeswani** [comment]
[PrestigeDevop](https://github.com/PrestigeDevop) It is hard to tell why it throws that error.

Could you check if the cpu nuget package works for you? I am not sure how I can debug this.

**Comment by PrestigeDevop** [comment]
<!DOCTYPE html>
<HTML>
<head>
</head>
<body>


  | Name | Value | Type
-- | -- | -- | --
◢ | this | {Microsoft.ML.OnnxRuntimeGenAI.Model} | Microsoft.ML.OnnxRuntimeGenAI.Model



</body>
</HTML>

<!DOCTYPE html>
<HTML>
<head>

it seems the tokenizer is null for some reasons ,
</head>
<body>


  | Name | Value | Type
-- | -- | -- | --
  | tokenizer | null | Microsoft.ML.OnnxRuntimeGenAI.Tokenizer



</body>
</HTML>

tho the model path that passed into the function isn't ``` E:onnxGen\Phi-3-mini-4k-instruct-onnx\cpu_and_mobile\cpu```

[Microsoft.ML.OnnxRuntimeGenAI.decompiled.zip](https://github.com/microsoft/onnxruntime-genai/files/15159224/Microsoft.ML.OnnxRuntimeGenAI.decompiled.zip)

I don't how to debug either , but I've stumbled upon a window in vs that show pdb symbol details but couldn't find it again it might have useful details it show me lines like    ``` C:\Users\hi\AppData\Local\Temp\SymbolCache\netstandard.pdb```

**Comment by PrestigeDevop** [comment]
![image](https://github.com/microsoft/onnxruntime-genai/assets/85388342/d850f788-e216-41c1-b594-ef1a196f7fa9)
 it seems that the version is broken you need to download both Microsoft.ML.OnnxRuntimeGenAI.Managed and Microsoft.ML.OnnxRuntimeGenAI with the version 0.2.0-rc4
 
 altho i'm sure I've already done this but probably not both have consistent version ? the application runs on my machine for now

**Comment by baijumeswani** [comment]
Seems it was a version issue. I'm closing this. Please reopen if the problem persists or you have more questions.
