### ISSUE TITLE
Phi-3 genai_config in .NET requiring to modification

### ISSUE THREAD

**Issue by aksoftware98** [microsoft/onnxruntime-genai#359]
While trying to load phi-3-mini-4k-instruct using ONNX Runtime Gen AI for **.NET**. 
the load model method is failing saying not supported property:
``"eos_token_id": [ 32000, 32001, 32007 ]`` 

And the ``type`` property too, the default value for phi-3 is ``phi3``.

I managed to get it work by removing the ``eos_token_id`` array and modifying ``type`` to ``phi`` instead of ``phi3``
Maybe that needs to be mentioned somewhere.

**Comment by baijumeswani** [comment]
My guess based on your description is that you're not using the correct library version from PyPI. Please use the pre-release version for runnning phi-3 using

```
# For CPU
pip install --pre onnxruntime-genai

# For CUDA
pip install --pre -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/ onnxruntime-genai-cuda

``` 

The current pre-release version is 0.2.0-rc4.

**Comment by lavinders** [comment]
Above tip worked for me! Was hitting the same issue when trying to run onnx runtime project with phi-3 model.

Agree it should be mentioned in the sample.

**Comment by aksoftware98** [comment]
> My guess based on your description is that you're not using the correct library version from nuget. Please use the pre-release version for phi-3: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntimeGenAI/0.2.0-rc4
> 
> The current pre-release version is 0.2.0-rc4.

Updated 5 days! Alright, awesome, because I tried a lot but yeah now it makes sense, and it's working fine!
Thanks!
