### ISSUE TITLE
Huggingface Chat error for Phi3 ONNX

### ISSUE THREAD

**Issue by parinitarahi** [microsoft/onnxruntime-genai#374]
Is the chat template working for Phi3 model at HF. I see the tokenizer config not found message. 

 https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx

![image](https://github.com/microsoft/onnxruntime-genai/assets/101819959/585d6546-5691-4c3b-99f7-12cf0fac9f02)

**Comment by yufenglee** [comment]
It should only work for transformer python model.
