### ISSUE TITLE
Multi-target with .NET Standard 2.0 and .NET runtimes

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/onnxruntime-genai#382]
Since you're targeting .NET standard, it'd be great to see multi-target support for .NET Standard 2.0 in order to support UWP and .NET Framework to increase reach of availability of these model tools.

You can see this is the general recommendation in the cross-platform guidance support doc here: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

There are NuGet packages for allowing for Span for instance for .NET Standard 2.0 which can be included for that target, for instance, see this example from the .NET Community Toolkit: https://github.com/CommunityToolkit/dotnet/blob/7b53ae23dfc6a7fb12d0fc058b89b6e948f48448/src/CommunityToolkit.HighPerformance/CommunityToolkit.HighPerformance.csproj#L28-L37

You could also multi-target the newer runtimes as well this way to have them better optimize performance when applications are targeting those runtimes. E.g. `<TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0</TargetFrameworks>` ([from here also](https://github.com/CommunityToolkit/dotnet/blob/7b53ae23dfc6a7fb12d0fc058b89b6e948f48448/src/CommunityToolkit.HighPerformance/CommunityToolkit.HighPerformance.csproj#L4)).

**Comment by natke** [comment]
Thank you for this @michael-hawker. We are looking into making these changes

**Comment by MadTekN1** [comment]
> Thank you for this @michael-hawker. We are looking into making these changes

Awesome! I would love having the ability to run genai on .Net Framework 4.8 :D
