### ISSUE TITLE
Created onnx version of ChatQA-1.5-8B model with Unknown value: pad_token_id error on inferencing

### ISSUE THREAD

**Issue by AshD** [microsoft/onnxruntime-genai#384]
Model: https://huggingface.co/nvidia/ChatQA-1.5-8B
Conversion Command: python -m onnxruntime_genai.models.builder -m ./ChatQA-1.5-8B -o chatqacpu -p int4 -e cpu -c cache

Runs without errors and creates the onnx model. 

Ran the onnx model. C# exception: 
`Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: 'Error encountered while parsing 'C:\AI\onnx\chatqacpu\genai_config.json' JSON Error: Unknown value: pad_token_id at line 33 index 26'`

Thanks,
Ash

**Comment by natke** [comment]
Hi @AshD We are looking into this

**Comment by baijumeswani** [comment]
@AshD what version of onnxruntime-genai are you using?

**Comment by AshD** [comment]
Microsoft.ML.OnnxRuntimeGenAI.DirectML 0.2.0-rc4

**Comment by kunal-vaishnavi** [comment]
The `genai_config.json` file shows a list of pad token ids rather than a single value. This will require a change in ONNX Runtime GenAI to support a list of pad token ids. A similar change was made [here](https://github.com/microsoft/onnxruntime-genai/pull/284) to support a list of EOS token ids.

**Comment by AshD** [comment]
Thanks for the fix. I did a github pull of the latest code and created a new model.
python builder.py -m ./ChatQA-1.5-8B -o chatqa -p int4 -e dml -c cache

When running the newly created model, I get a new error. 

`Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: 'NO_SUCH_FIELD: The JSON field referenced does not exist in this object.'` 

Using Microsoft.ML.OnnxRuntimeGenAI.DirectML 0.2.0-rc4 in C# when running.

**Comment by AshD** [comment]
Exception Stack Trace: 
```
 	Microsoft.ML.OnnxRuntimeGenAI.dll!Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(nint nativeResult) Line 20	C#
>	Microsoft.ML.OnnxRuntimeGenAI.dll!Microsoft.ML.OnnxRuntimeGenAI.Tokenizer.Tokenizer(Microsoft.ML.OnnxRuntimeGenAI.Model model) Line 14	C#
 	AILocal.dll!AILocal.Onnx.OnnxLlmChatCompletion.Init() Line 25	C#
```

**Comment by natke** [comment]
Hey @AshD can you post your config here please?

**Comment by AshD** [comment]
I got the latest python builder source and recreated the model and it works now!

Uploaded the model here - https://huggingface.co/FusionQuill/Llama3-ChatQA-1.5-8B-Onnx
