### ISSUE TITLE
Finetuned Phi3 built with the model builder give gibberish ouput due to lack of support for LoRA

### ISSUE THREAD

**Issue by Pathos0925** [microsoft/onnxruntime-genai#399]
Has the model builder been proven to work with fine-tuned Phi3 models as suggested in the link in the HF card? 
https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/resolve/main/sample_finetune.py

If it has then I am probably doing something wrong in the finetuning.

**Comment by natke** [comment]
Hi @Pathos0925, can you please share the model builder command and they command you are running and any errors that you get?

**Comment by kunal-vaishnavi** [comment]
The sample finetuning script appears to be [using LoRA](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/920b6cf52a79ecff578cc33f61922b23cbc88115/sample_finetune.py#L99), which changes how the resulting ONNX model looks and runs. LoRA is not currently supported in the model builder but support for LoRA will be coming soon. A preview of how the APIs will look for running models with LoRA/QLoRA can be found [here](https://github.com/microsoft/onnxruntime-genai/pull/370).

**Comment by natke** [comment]
Closing this issue for now. Please check back for LoRA support
