### ISSUE TITLE
Loading an `og.Model` sometimes throws a segfault

### ISSUE THREAD

**Issue by Ben-Epstein** [microsoft/onnxruntime-genai#409]
This is very confusing, but depending on which modules you've imported before importing `onnxruntime_genai`, loading the model will throw a segfault.

Here's an example

```py
import vertexai
import onnxruntime_genai as og

m = og.Model("Phi-3-mini-128k-instruct-onnx/cuda/cuda-int4-rtn-block-32")  # segfault
```

but if i import `onnxruntime_genai` first, i don't see a segfault
```py
import onnxruntime_genai as og
import vertexai

m = og.Model("Phi-3-mini-128k-instruct-onnx/cuda/cuda-int4-rtn-block-32")  # loads fine
```

I don't know which other libraries cause this, or the root library giving the error. But in my codebase it was traced down to `vertexai`...

Happy to provide more help if needed. Thanks!

**Comment by baijumeswani** [comment]
This seems to be the same issue as [#](https://github.com/microsoft/onnxruntime-genai/issues/257).

Could you please try using version 0.2.0rc6? It should be resolved in that python package.

**Comment by Ben-Epstein** [comment]
Thank you @baijumeswani! That worked perfectly. I'll close out the ticket
