### ISSUE TITLE
Extensions for LLM

### ISSUE THREAD

**Issue by hannespreishuber** [microsoft/onnxruntime-genai#442]
the idea. Write a litte app - put it on a raspberry to swith lights on or off
Would start with phi-3 (which works as .net app) extend with whisper.. 
Would need a feature like embeddings or functions
Had a look at semantic kernel but needs a http Rest endpoint, which makes no sense.
Any advice?

**Comment by yufenglee** [comment]
I didn't have experience to run a LLM on raspberry device. How does the perf look like, for example to run a phi3 model?

**Comment by natke** [comment]
@hannespreishuber Your app idea sounds interesting! Can you elaborate on the flow of the application a little more?

Did you try to run phi-3 on raspberry pi already?

Fyi, we are in the process of adding support for whisper.

**Comment by baijumeswani** [comment]
Closing the issue. Please re-open if this is still relevant.
