### ISSUE TITLE
Gemma-2b-it EP:CPU int4 ONNX model generated using ONNXruntime-genai throws an error

### ISSUE THREAD

**Issue by jmopuri-Intel** [microsoft/onnxruntime-genai#459]
Hi,
    I have generated the Gemma-2b-it ONNX model for EP 'CPU' and precision 'int4' using onnxruntime_genai.models.builder. It seemed like it successfully generated the model and the files in that folder all seem fine. However, when try to use that model, I get the following error:

_Node input '/model/layers.0/attn/k_proj/repeat_kv/Transpose_2/output_0' is not a graph input, initializer, or output of a previous node_

I am stuck and not sure what to do. Please help! Did anyone generate ONNX model for Gemma? If so, please share the steps.

Thanks,
Jagan

**Comment by kunal-vaishnavi** [comment]
Can you re-generate the `Gemma-2b-it` ONNX model by cloning the main branch of ONNX Runtime GenAI and running the "from source" version of your command?

Example:
```
# Your original command (i.e. "from wheel" version):
$ python3 -m onnxruntime_genai.models.builder -m google/gemma-2b-it -o ./gemma_2b_it -p int4 -e cpu

# New command to try (i.e. "from source" version):
$ git clone https://github.com/microsoft/onnxruntime-genai
$ cd onnxruntime-genai/src/python/py/models/
$ python3 builder.py -m google/gemma-2b-it -o ./gemma_2b_it -p int4 -e cpu
```

**Comment by jmopuri-Intel** [comment]
Thanks for the quick response! I will try soon and report the result here.

**Comment by jmopuri-Intel** [comment]
yes, that worked. Thank you!

**Comment by jmopuri-Intel** [comment]
yes, that worked.
