### ISSUE TITLE
Feature Request: Specify seed in python SDK

### ISSUE THREAD

**Issue by Ben-Epstein** [microsoft/onnxruntime-genai#463]
I've been using phi3-128k-onnx and it's been fantastic, thank you for your work!

I see that you specify a seed in the c bindings, would you be able to expose that to the python bindings?

**Comment by natke** [comment]
Glad to hear that you are enjoying it!

The missing seed from the Python API looks an omission on our part. We will get that added in.

**Comment by baijumeswani** [comment]
Sorry, I missed this. I think setting a random seed for ort genai can be done though the generator params' search options. Details can be found from [this pull request](https://github.com/microsoft/onnxruntime-genai/pull/250).

```python
params = og.GeneratorParams(model)
params.set_search_options(random_seed=8888)
```

Please give that a try. Let me know if this issue can be closed once you try it out.
