### ISSUE TITLE
phi-3-tutorial direct ML are not working properly

### ISSUE THREAD

**Issue by invent00** [microsoft/onnxruntime-genai#476]
![image](https://github.com/microsoft/onnxruntime-genai/assets/64936321/e347bc88-66b6-46ac-8a46-d7d964093c13)

https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi-3-tutorial.md

Phi-3 tutorial are not working properly. There is no error but no output.
I checked it on my CUDA(Geforce 3070) environment and AMD APU(Ryzen 7 5850U). 

pip environments are following.

(venv) PS C:\Users\invent\Documents\sisakucode\onnx_directML> pip list
Package                    Version
-------------------------- --------
certifi                    2024.2.2
charset-normalizer         3.3.2
colorama                   0.4.6
filelock                   3.14.0
fsspec                     2024.5.0
huggingface-hub            0.23.0
idna                       3.7
inquirerpy                 0.3.4
numpy                      1.26.4
onnxruntime-genai-directml 0.2.0rc7
packaging                  24.0
pfzy                       0.3.4
pip                        22.0.4
prompt-toolkit             3.0.43
PyYAML                     6.0.1
requests                   2.31.0
setuptools                 58.1.0
tqdm                       4.66.4
typing_extensions          4.11.0
urllib3                    2.2.1
wcwidth                    0.2.13

is there any additional requirements?

**Comment by invent00** [comment]
Hi, Thank you for your support. 
New version(0.2.0) works properly in each environtment(cuda/amd apu)

The environment used is left for reference.

================================
certifi==2024.2.2
charset-normalizer==3.3.2
colorama==0.4.6
filelock==3.14.0
fsspec==2024.5.0
huggingface-hub==0.23.0
idna==3.7
inquirerpy==0.3.4
numpy==1.26.4
onnxruntime-genai==0.2.0
onnxruntime-genai-directml==0.2.0
packaging==24.0
pfzy==0.3.4
prompt-toolkit==3.0.43
PyYAML==6.0.1
requests==2.31.0
tqdm==4.66.4
typing_extensions==4.11.0
urllib3==2.2.1
wcwidth==0.2.13

**Comment by natke** [comment]
Awesome! thank you for checking back in
