### ISSUE TITLE
RuntimeError: Unsupported model_type in config.json: phi3small

### ISSUE THREAD

**Issue by guidevops** [microsoft/onnxruntime-genai#499]
I'm fallowing this guide: https://onnxruntime.ai/docs/genai/tutorials/phi3-python.html#run-with-nvidia-cuda

i installed the package using:
```bash
$ pip install --pre onnxruntime-genai-cuda --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
Looking in indexes: https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
Requirement already satisfied: onnxruntime-genai-cuda in /srv/venvs/onnx/lib/python3.10/site-packages (0.2.0)
```

```bash
$ nvidia-smi --version
NVIDIA-SMI version  : 555.42.02
NVML version        : 555.42
DRIVER version      : 555.42.02
CUDA Version        : 12.5
Python version 3.10.0
pip version 24.0
```

**Comment by baijumeswani** [comment]
Which model are you using?

**Comment by baijumeswani** [comment]
The package has been published. You can use the same command to get the latest package 0.3.0-rc1

```
pip install --pre onnxruntime-genai-cuda --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/
```

**Comment by guidevops** [comment]
I was using phi-3-small cuda-int4-rtn-block-32 version, i have a rtx 2060 with 6gb of vram.
Now it worked, i haven't been able to run it yet because I don't have enough video memory, but the model was loaded. thank you!
i will try the cpu version.

**Comment by guidevops** [comment]
I have enough vram to load the model but when trying to generate a response the script fail because is no able to allocate more vram, exist any way that i can load the model in gpu and use ram to store the cache ?
