### ISSUE TITLE
cannot install onnxruntime-genai on CPU based, Intel Mac

### ISSUE THREAD

**Issue by sivang** [microsoft/onnxruntime-genai#518]
The instructions in docs are as follows:

![image](https://github.com/microsoft/onnxruntime-genai/assets/310789/08de3c49-2023-43b9-944f-e53a99da0a63)

However, when trying to follow the package is not found int he index:

```
(venv) sivan@darwin:~/VitakkaProjects/ONNX$ pip install --pre onnxruntime-genai
ERROR: Could not find a version that satisfies the requirement onnxruntime-genai (from versions: none)
ERROR: No matching distribution found for onnxruntime-genai
```

Please provide the correct / alternative way to install or instructions how to build from source.

On an Intel Mac, 
```
Darwin darwin.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64
```

```
(venv) sivan@darwin:~/VitakkaProjects/ONNX$ xcode-select --version
xcode-select version 2406.
```

```
(venv) sivan@darwin:~/VitakkaProjects/ONNX$ python --version
Python 3.12.2
```

But also tried on Python 3.11.8

```[tasklist]
### Tasks
```

**Comment by itsclint** [comment]
I am having the same issue on an M1 pro 2021 too

**Comment by pomi601** [comment]
See #308. Building from source is an alternative.

**Comment by yeyujujishou** [comment]
pip install onnxruntime-genai --pre
ERROR: Could not find a version that satisfies the requirement onnxruntime-genai (from versions: none)
ERROR: No matching distribution found for onnxruntime-genai

**Comment by baijumeswani** [comment]
We have not published mac os packages yet. This is on our roadmap, but I do not have a timeline that I can share yet. We probably will get to this in the 0.4.0 release.

As suggested in the earlier comment, please build from source in the meantime. I'll close this issue now.
