### ISSUE TITLE
[Feature Request] phi-3-small-128k-onnx-cpu model

### ISSUE THREAD

**Issue by Ben-Epstein** [microsoft/onnxruntime-genai#519]
The onnx-gpu model for phi-3-small-128k is great, a perfect balance of quality and speed. Is there a plan to support a cpu version?

Thanks!

**Comment by andliang** [comment]
> We intend to add a CPU kernel as well in the near future. Once that is added, we will be able to support Phi-Small on CPU as well.

Interesting... according to these two pages [Run Phi-3 language models with the ONNX Runtime generate() API](https://onnxruntime.ai/docs/genai/tutorials/phi3-python.html) and [Run the Phi-3 vision model with the ONNX Runtime generate() API](https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html), they can run on CPU. Am I missing something?

Just a FYI, Im new to Python/Cuda/Pytorch/etc and this ecosystem.

**Comment by baijumeswani** [comment]
> Interesting... according to these two pages [Run Phi-3 language models with the ONNX Runtime generate() API](https://onnxruntime.ai/docs/genai/tutorials/phi3-python.html) and [Run the Phi-3 vision model with the ONNX Runtime generate() API](https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html), they can run on CPU. Am I missing something?

All phi3 family models except for phi3-small can be run on CPU. The linked documentation doesn't mention the phi3-small model. Maybe we should explicitly call it out in the doc.

**Comment by kunal-vaishnavi** [comment]
The support for Phi-3 small on CPU has been added in [this PR](https://github.com/microsoft/onnxruntime-genai/pull/710). You can follow the instructions in the PR to get your environment and files set up and then use those changes to generate a Phi-3 small ONNX model for CPU.
