### ISSUE TITLE
Looking for onnx version of microsoft/Phi-3-vision-128k-instruct

### ISSUE THREAD

**Issue by AshD** [microsoft/onnxruntime-genai#527]
Looking for onnx version of microsoft/Phi-3-vision-128k-instruct
Onnx files don't seem to be on Hugging Face.

Also, Does the onnxruntime-genai support multiple GPUs on the same PC?

Thanks,
Ash

**Comment by AshD** [comment]
Thanks @baijumeswani

**Comment by eres313** [comment]
Do you have the paper published about the architecture and details of Phi3-Vision model?

**Comment by baijumeswani** [comment]
The [Phi-3 Technical Report](https://arxiv.org/abs/2404.14219) should have details on the model architecture.

**Comment by baijumeswani** [comment]
The onnx version of the vision model has been published. Please refer to this tutorial on getting started: https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html.

Closing this issue now. Please open another issue if you have further questions.

**Comment by zhanghanduo** [comment]
> The onnx version of the vision model has been published. Please refer to this tutorial on getting started: https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html.
> 
> Closing this issue now. Please open another issue if you have further questions.

Thanks for the nice demo code. I could make it work on onnxruntime_genai cpu version. When I run with the onnxruntime-genai-cuda (0.3.0rc2) on Windows, there will be the error (module 'onnxruntime_genai' has no attribute 'Model') for the line of code `model = og.Model(args.model_path)`
