### ISSUE TITLE
Is OgaGenerator a one-time object?

### ISSUE THREAD

**Issue by MasterYi1024** [microsoft/onnxruntime-genai#538]
I'm writing a c++ demo to use OgaGenerator to generate text with chat history, so I rely on the ability of the kv cache to reduce the generation time. But I found (in the code genai already has) that OgaGenerator seems to be a one-time object and cannot be reused. And the KV-Cache class indirectly belongs to OgaGenerator. If OgaGenerator is disposable, then after creating a new generator, the original KV-Cache will no longer be useful.

May I ask if I understand correctly? I have read the document for onnxruntime.ai, is there anything I missed?

I found this discussion, but it doesn't seem to have much content.
https://github.com/microsoft/onnxruntime-genai/discussions/416

Thank you in advance：）

**Comment by yufenglee** [comment]
@MasterYi1024 , yes, you're right. OgaGenerator is a one-time object. We will add interactive decoding to support your scenario.

**Comment by MasterYi1024** [comment]
@yufenglee Thank you so much for your reply : )

Feel free to close this issue or something.

**Comment by arpit-saxena** [comment]
Hey @yufenglee, has any functionality been added to support this scenario?

**Comment by baijumeswani** [comment]
We have recently added support for continuous decoding. Please take a look at this PR that introduced the support https://github.com/microsoft/onnxruntime-genai/pull/867
