### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'onnxruntime-genai' or one of its dependencies (Visual Studio 2022)

### ISSUE THREAD

**Issue by dsjlee** [microsoft/onnxruntime-genai#539]
I tried running .NET 6 app (C#) using nuget package Microsoft.ML.OnnxRuntimeGenAI.Cuda v0.2.0
Visual Studio 2022 gives this error when running in Debug mode X64 target.

System.DllNotFoundException: 'Unable to load DLL 'onnxruntime-genai' or one of its dependencies: The specified module could not be found. (0x8007007E)'

Exception thrown: 'System.DllNotFoundException' in Microsoft.ML.OnnxRuntimeGenAI.dll
An exception of type 'System.DllNotFoundException' occurred in Microsoft.ML.OnnxRuntimeGenAI.dll but was not handled in user code
Unable to load DLL 'onnxruntime-genai' or one of its dependencies: The specified module could not be found. (0x8007007E)

I tried repair installing VC redist for VS and also tried installing different version of CUDA Toolkit: v11.8, v12.4, v12.5 but to no avail.

**Comment by tianleiwu** [comment]
CUDA 11.8, cuDNN 8.9.* and latest [VC runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

**Comment by BrainSlugs83** [comment]
> CUDA 11.8, [cuDNN 8.9.* for CUDA 11.x](https://developer.nvidia.com/rdp/cudnn-archive) and latest [VC runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).
> 
> Make sure to set path environment variable so that CUDA and cuDNN dlls can be found.

I was under the impression that The ONNX runtime was cross platform and supported AMD GPUs as well as NPU/TPUs and CPUs.

Is there a way to reference this package generically and have it "just work" at runtime, regardless of the backend?

**Comment by dsjlee** [comment]
> I was under the impression that The ONNX runtime was cross platform and supported AMD GPUs as well as NPU/TPUs and CPUs.
> 
> Is there a way to reference this package generically and have it "just work" at runtime, regardless of the backend?

If you look at Phi-3 mini models MS published. There's three versions for ONNX model. directml, cuda, cpu/mobile. DirectML version seems to be GPU vendor neutral where was CUDA version is Nvidia GPU specific model.

I was able to run DirectML version of the ONNX model on my AMD GPU. Now, I'm trying to run CUDA version of the ONNX model on my Nvidia GPU and Visual Studio is giving me grief.

Depending on whether you want to use DirectML version or CUDA version of ONNX model, it seems I have to use different nuget package for ONNX runtime for running .NET app
- Microsoft.ML.OnnxRuntimeGenAI.DirectML
- Microsoft.ML.OnnxRuntimeGenAI.Cuda

For running ONNX model on NPU, I think you have to specifically prepare the ONNX model for specifc NPU vendor.

**Comment by dsjlee** [comment]
> CUDA 11.8, [cuDNN 8.9.* for CUDA 11.x](https://developer.nvidia.com/rdp/cudnn-archive) and latest [VC runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).
> 
> Make sure to set path environment variable so that CUDA and cuDNN dlls can be found.

Just reporting, I installed cuDNN 8.9x for CUDA 11 and tried adding PATH variable for it in various ways but it did not fix the error.

**Comment by baijumeswani** [comment]
What fixed it for me was to put the CUDA 11.8 bin path above any other cuda version bin path in the PATH. Here is my env variable:

![image](https://github.com/microsoft/onnxruntime-genai/assets/12852605/8a6fc606-5a4c-4d65-a1fa-10bc86a4131e)

This worked for me. Could you give it a try? Also, make sure the cudnn dlls are inside the bin CUDA toolkit bin folder:

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin

**Comment by dsjlee** [comment]
> What fixed it for me was to put the CUDA 11.8 bin path above any other cuda version bin path in the PATH. Here is my PATH env variable:
> 
> This worked for me. Could you give it a try? Also, make sure the cudnn dlls are inside the bin CUDA toolkit bin folder:
> 
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin

I checked to see 11.8 is the only PATH entry as I had already uninstalled v12.x before installing 11.8. I also checked cuDNN files were copied to Toolkit's corresponding folders as cuDNN install instruction stated. Still didn't work but thanks anyway.

I don't need this to work so feel free to close this issue.

**Comment by baijumeswani** [comment]
Please raise another issue if this continues to be a problem.
