### ISSUE TITLE
Inspect GeneratorParams (and possible other class) in C# & Java

### ISSUE THREAD

**Issue by skyline75489** [microsoft/onnxruntime-genai#545]
Currently the C bindings does not expose APIs that can inspect a `GeneratorParams`. This makes debugging quite painful in the managed world.

**Comment by baijumeswani** [comment]
I think we had an internal discussion at some point about this. I agree that it would be nice to inspect the generator params, but this is not currently on the roadmap. The most we can do at this point is to print the search params that are being used. The flag for this is already exposed through:

```py
og.set_log_options(enabled=True, generate_next_token=True)
```

As can be seen here https://github.com/microsoft/onnxruntime-genai/blob/dac90d557dbd90c816cb4a44f39367346bca1c1c/src/generators.cpp#L184-L192.
