### ISSUE TITLE
"Not enough memory resources are available to complete this operation" error when running `Phi-3-mini-128k-instruct-onnx` on DirectML without explicitly specifying 'max_length' in search options

### ISSUE THREAD

**Issue by jackylu0124** [microsoft/onnxruntime-genai#550]
I am running the `Phi-3-mini-128k-instruct-onnx` model on DirectML with the example `phi3-qa.py` script ([https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi3-qa.py](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi3-qa.py)), and the only changes that I have made to the script is that I commented out the if-block setting `search_options['max_length'] = 2048` so that it uses the maximum context length supported by the model (131072 in this case) by default. I ran into the following out of memory error as soon as I typed in a simple input prompt "Hello!". However, this error does not occur when I run the `Phi-3-mini-4k-instruct-onnx` model without explicitly specifying the `max_length` search option. Please see the full error logs below.

Error Logs (parts of the exact paths are replaced with `xxx` for privacy reasons):
```
PowerShell 7.4.2
PS D:\xxx\xxx\xxx\onnx_test> python phi3-qa.py -m .\Phi-3-mini-128k-instruct-onnx\directml\directml-int4-awq-block-128
Input: Hello!
Traceback (most recent call last):
  File "D:\xxx\xxx\xxx\onnx_test\phi3-qa.py", line 97, in <module>
    main(args)
  File "D:\xxx\xxx\xxx\onnx_test\phi3-qa.py", line 47, in main
    generator = og.Generator(model, params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime_genai.onnxruntime_genai.OrtException: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlCommittedResourceAllocator.cpp(22)\onnxruntime.dll!00007FFB97371FF1: (caller: 00007FFB97354190) Exception(1) tid(1824) 8007000E Not enough memory resources are available to complete this operation.
```

Package Version: `onnxruntime-genai-directml 0.3.0rc2`
GPU: RTX 3090

**Comment by baijumeswani** [comment]
onnxruntime-genai tries to allocate the KV cache based on the max_length. In the absence of the max_length being set, the context length (128K) is used to allocate memory for the KV cache. As you can imagine, this is a lot of memory, and your machine most likely does not have this available.

Two things you can do in such scenarios:
1. Set a max_length to whatever you think your application needs.
2. Turn off past present buffer sharing in the genai config. When this setting is turned off, the KV cache is dynamically allocated as needed on each step. This may lead to performance degradation though.

**Comment by jackylu0124** [comment]
Hi @baijumeswani,

Got it, thank you very much for the clarification!
