### ISSUE TITLE
Phi3-Vision ONNX models 

### ISSUE THREAD

**Issue by eres313** [microsoft/onnxruntime-genai#554]
Hi,

Thanks for sharing ONNX models recently. 

We got 3 ONNX models, vision, text embedder and text generator models.

What I want to achieve is running those 3 ONNX models separately and passing results from one model to another.

After I get `visual_features` from vision model and `inputs_embeds` from text embedder model, I want to pass to the text generator model via ONNXRUNTIME in Python to generate tokens.

How can I achieve this?

Thanks in advance.

**Comment by baijumeswani** [comment]
onnxruntime-genai tries to abstract the lower-level invocations away and only offers a high-level API that manages the state across the three onnx models.

It seems what you're interested in is a way to use the high-level API from onnxruntime-genai in conjunction with the low-leve API from onnxruntime? May I ask what scenario you're trying to tackle by using this workflow?

**Comment by eres313** [comment]
Thank you for your reply.

The idea is I am building a pipeline where I need to load models separately with `onnxruntime` and pass outputs of one model to the input of the next. But I need to do this purely in Python

**Comment by baijumeswani** [comment]
@eres313 onnxruntime-genai considers the model folder as a single model and does not plan on offering utilities to query intermediate results from the output of individual models for the time being.

**Comment by web3nomad** [comment]
> Hi,
> 
> Thanks for sharing ONNX models recently.
> 
> We got 3 ONNX models, vision, text embedder and text generator models.
> 
> What I want to achieve is running those 3 ONNX models separately and passing results from one model to another.
> 
> After I get `visual_features` from vision model and `inputs_embeds` from text embedder model, I want to pass to the text generator model via ONNXRUNTIME in Python to generate tokens.
> 
> How can I achieve this?
> 
> Thanks in advance.


You can achieve this by combine the visual features and text embeddings as required by your text generator model. Then feed the combined input into the text generator model to produce output tokens.

I've been also working on the same ONNX models recently, but in Rust. You might find this PR for reference: https://github.com/pykeio/ort/pull/291/
