### ISSUE TITLE
Does onnxruntime or onnxruntime_genai support tool_calling?

### ISSUE THREAD

**Issue by jivaniyash** [microsoft/onnxruntime-genai#561]
### Discussed in https://github.com/microsoft/onnxruntime-genai/discussions/542

<div type='discussions-op-text'>

<sup>Originally posted by **jivaniyash** May 29, 2024</sup>
I am looking to use phi-3 model (using ONNX runtime) to integrate function_calling / tool_calling? Is there any documentation/API to add tool_calling along the prompt? Also, how can I change the system prompt?</div>

**Comment by baijumeswani** [comment]
Could you share more details on the tool_calling functionality? Any open-source document/code where this is done?

**Comment by baijumeswani** [comment]
Will close this. We can continue discussion in the discussions thread.
