### ISSUE TITLE
Add ARM64 support.

### ISSUE THREAD

**Issue by azchohfi** [microsoft/onnxruntime-genai#637]
Still can't leverage the DirectML version of this package (Microsoft.ML.OnnxRuntimeGenAI.DirectML) on ARM64 machines (Copilot+ PCs):
https://nuget.info/packages/Microsoft.ML.OnnxRuntimeGenAI.DirectML/0.3.0

**Comment by liuyunms** [comment]
Support for ARM64 machines is coming soon. Please stay tuned for future updates.

**Comment by goxia** [comment]
> Support for ARM64 machines is coming soon. Please stay tuned for future updates.

Is the version 0.3.0 supported Arm64? I saw this information from the introductory document. Thanks!

**Comment by IntranetFactory** [comment]
@liuyunms it seems that my definition of soon differs from yours. Do you have any ETA ?

**Comment by hmartinez82** [comment]
It seems that this made into the main branch, but I can't get past this:
```
C:\Dev\Github\onnxruntime-genai\src\models\model.h(10): fatal error C1083: Cannot open include file: 'dml_provider_factory.h': No such file or directory
```
There are several of those lines. I'm trying to build genai for DirectML.
I tried using `build.bat (with --use_dml)` , I tried running CMake myself and I tried using the `windows_arm64_directml_release` CMake preset. They all fail to build exactly the same way.

@baijumeswani what could I be doing wrong?

**Comment by dav3shanahan** [comment]
does this have arm64 yet or no?

**Comment by RodDaSilvaWCO** [comment]
Is there any progress on this issue since Aug/24?  I too wish to use **Microsoft.ML.OnnxRuntimeGenAI.DirectML** on ARM64 machines.  Thanks.

**Comment by sourcesync** [comment]
@RodDaSilvaWCO Did you make any progress on this?

I am able to build onnxruntime-genai from source on a Windows11 ARM machine (with Snapdragon CPU and Adreno GPU ).

It builds a WHL file successfully.  

Unfortunately, if I try to install this WHL into a Python3.11 environment, it says:

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml>=1.20.1 (from onnxruntime-genai-directml) (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml>=1.20.1

Then, if I try to build onnxruntime with DML support, I then get lots unit test errors.

**Comment by cylin577** [comment]
2 years later but still no ARM64 support in the PyPi release, what are you guys (Microsoft) doing? Busy intergrating the useless Copilot into Windows??????

**Comment by baijumeswani** [comment]
@cylin577 onnxruntime-genai and onnxruntime support for DirectML is in maintenance mode. No active dml related development is expected. You can use ort-genai-winml  to run models across vendors.
