### ISSUE TITLE
ImportError for genai library in python on DirectML EP with 0.3.0 release

### ISSUE THREAD

**Issue by thevishalagarwal** [microsoft/onnxruntime-genai#638]
I updated the onnxruntime_genai python library to the latest 0.3.0 release and getting the following import error. This is on DirectML backend

```sh
     from onnxruntime_genai.onnxruntime_genai import *
ImportError: DLL load failed while importing onnxruntime_genai: A dynamic link library (DLL) initialization routine failed.
```

**Comment by baijumeswani** [comment]
This is a known error. My guess is that you're using conda on Windows?

Please see this issue for more details: https://github.com/microsoft/onnxruntime-genai/issues/555

TLDR: run `conda install conda-forge::vs2015_runtime` should fix the issue.

**Comment by thevishalagarwal** [comment]
Yes, this worked. Thanks!
