### ISSUE TITLE
Support for Vision models like Phi3 Vision and Microsoft's Florence 2?

### ISSUE THREAD

**Issue by BrainSlugs83** [microsoft/onnxruntime-genai#645]
Just what the title says.  Will there be support for Phi 3 Vision and Florence 2?

**Comment by baijumeswani** [comment]
@BrainSlugs83 We already have support for Phi3 Vision. Please see the tutorial here: https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html

We have added Florence to our roadmap, but not sure if it will be prioritized for the next release.

**Comment by natke** [comment]
@BrainSlugs83 We have a Discussion open for Florence-2 V. https://github.com/microsoft/onnxruntime-genai/discussions/categories/model-support

Please try Phi-3 vision and let us know how you go.
