### ISSUE TITLE
Conda package release ?

### ISSUE THREAD

**Issue by Glider95** [microsoft/onnxruntime-genai#647]
Hello,

Following a discussion in this thread: https://github.com/microsoft/onnxruntime-genai/discussions/636, I am adding a request  for « feature » here and to have a bit more visibility.

Is there any plan to release a Conda package of onnxruntime-genai or would it be added to onnxruntime when mature enough ? If the second, any expected timeline ?

Cheers,

**Comment by natke** [comment]
Hi @Glider95,

We do not currently have publishing to conda on our roadmap, but would be happy to support you if you wanted to contribute. I know you made some steps to get started. Is there a blocker we can help with?

**Comment by Glider95** [comment]
Hello @natke ,

I have look into it to do it myself, unfortunately it is out of competencies for now due all the dependencies with Cmake etc...
I will try to deep dive again when I have more time.

Best regards,

**Comment by natke** [comment]
Please reach out again when you ramp up on this @Glider95!
