### ISSUE TITLE
Unable to install and run Phiv3 vision

### ISSUE THREAD

**Issue by billSP2** [microsoft/onnxruntime-genai#652]
I've seen several others have issues installing phiv3 vision, but after following the instructions I was unsuccessful so decided to post my situation to solicit guidance.

Running on Windows 11 Laptop with Geforce RTX 3050 Ti Laptop GPU
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/3f712d6d-3e43-4c80-8f82-02bc624f779d)

Nvidia site says it supports CUDA.
I installed CUDA via windows installer
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/d30d6da8-5970-4cd4-aa81-81fc4191d934)

I installed CUDNN via pip install. List of installed packages provided in the pip list output command attached.
[list.txt](https://github.com/user-attachments/files/16025209/list.txt)

Validated the following CUDA_PATH
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/ddeef9ab-b843-4df3-94d7-ff60e204d9e1)

and PATH are set
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/9270b305-1ebe-4207-8eb4-c704e417f713)

I installed the genai cuda libraries
pip install onnxruntime-genai-cuda --pre --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/

I have installed the model cuda-fp16
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/d5fdd9d9-6330-4695-a486-4b10f9b8ebad)

Try running phi3v.py and receive the onnxruntime_genai module could not be found error. 
python phi3v.py -m "C:\cuda-fp16\phi-3-v-128k-instruct-vision.onnx"
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\onnxruntime_genai\__init__.py", line 10, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
ImportError: DLL load failed while importing onnxruntime_genai: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BillBaer\OneDrive - Support Partners\projects\cobra\GPT4Video\phi3\phi3v.py", line 12, in <module>
    import onnxruntime_genai as og
  File "C:\Python312\Lib\site-packages\onnxruntime_genai\__init__.py", line 18, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
ImportError: DLL load failed while importing onnxruntime_genai: The specified module could not be found.

I went to the python site packages directory for onnxruntime_genai and I don't see the onnxruntime_genai.dll file.
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/7bd014da-c6b7-41e4-931b-1ab082ab084c)
I've tried reinstalling the onnxruntime_genai_cuda multiple times but it does not seem to install that dll. 

Appreciate your help in guiding me on what I'm doing wrong?

**Comment by baijumeswani** [comment]
The problem seems to be the version of cuda you are using. onnxruntime-genai-cuda requires cuda 11.8 and cudnn 8.x for cuda 11.8.

If you would like to use cuda 12, you can install using:

```
pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ onnxruntime-genai-cuda
```

**Comment by billSP2** [comment]
Thank you, bajiumeswani. I went with your suggestion and went back to 11.8 of cuda and 8.x for cudnn. Here is validation of what I have. I first uninstalled cuda 12 and deleted the cudnn files from that install making it fresh.

![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/ecaac12c-781e-4732-a34a-340ceaf2a7c4)
I copied the files in this archive into the bin, lib and include folders.
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/ddddde83-7407-4a31-8ba9-6ec931d164ce)

I reinstalled the models into c:\cuda-fp16.
# Download just the FP16 model
$ huggingface-cli download microsoft/Phi-3-vision-128k-instruct-onnx-cuda --include cuda-fp16/* --local-dir .  --local-dir-use-symlinks False

I reinstalled onnxruntime
pip install --pre onnxruntime-genai-cuda --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-genai/pypi/simple/

Cleaned out the cuda packages installed in pip. Here is my latest list.
[pip list.txt](https://github.com/user-attachments/files/16037419/pip.list.txt)

Updated my path
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/ada447c3-fcc1-49d8-9e5f-23f89d9b2570)

Reinstalled the C++ redistributables just in case.

Wrote a small program to test the onnx package version
import onnxruntime_genai
print(f"onnxruntime version: {onnxruntime_genai.__version__}")
Here is the output
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/172bbc8b-c30d-41b7-9120-fc7a68ee6e75)

Tried running phi3v.py again and received load error 126 which looks to have gotten further into the code.
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/38f26f8d-f48a-4222-8848-de2313c6d002)

Here is my onnxruntime_genai folder.
![image](https://github.com/microsoft/onnxruntime-genai/assets/137107759/d5d6ffb9-ccd0-4c86-b050-56dfe340f088)

Any ideas what this new problem might be?

**Comment by baijumeswani** [comment]
onnxruntime requires cudnn 8.x for cuda 11.8. Download link: https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.7/local_installers/11.x/cudnn-windows-x86_64-8.9.7.29_cuda11-archive.zip/

**Comment by billSP2** [comment]
baijumeswani, thank you for all of your guidance and sorry I still had the wrong cudnn. I had grabbed the most recent archived version for that version, but apparently chose wrong. The script now works so thank you again. All the best. Bill

**Comment by ricoisme** [comment]
I installed cuda 11.8 and cudnn 8.9.7.29 on windows11 but still not work.
![image](https://github.com/microsoft/onnxruntime-genai/assets/17023972/1d150868-0f3f-44f9-af42-5dcca6daf002)
