### ISSUE TITLE
"Specified provider is not supported" when just loading models in C#

### ISSUE THREAD

**Issue by ray-linn** [microsoft/onnxruntime-genai#653]
I created a very simple code to use ONNXRuntime-GenAI, however it keeps error on create Model object.
The 1st error is "Access Violation" when call MSVC14P.dll, that issue disappeared after I installed the latest VC14 redist package. and now it throws exeception as "Specified provider is not supported"

Repro Steps
1.  download the Phi3  as  `huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include directml/* --local-dir .`
2.  Ensure onnx.model exists . and offer the full path "D:\MS\Models\directml\directml-int4-awq-block-128" for creating model object as following :
```
var ModelDir = Path.GetFullPath(@"D:\MS\Models\directml\directml-int4-awq-block-128");
Console.WriteLine("Loading Models from " + ModelDir);
Model? model = new(ModelDir);
Tokenizer? tokenizer = new(model);
```
confirmed - OnnxRuntimeGenAi.DirectML 0.3.0 installed.

3. Compile and run as X64, error popup .
4. the config.json is 

```
            "session_options": {
                "log_id": "onnxruntime-genai",
                "provider_options": [
                    {
                        "dml": {}
                    }
                ]
            },
```
5. Running GPU-z,  confirm my UMA intel 630 supports DirectML.

could you help to check why the provider doest not work?

**Comment by ray-linn** [comment]
Add more

1. Uninstall the OnnxRuntimeGenAi.DirectML and installed OnnxRuntimeGenAi 0.3.0.
2. Download the Phi3 CPU model again and just change model dir -then it work -

```
Loading Models from D:\MS\Models\cpu_and_mobile\cpu-int4-rtn-block-32-acc-level-4
 The capital of France is Paris.
```

**Comment by natke** [comment]
Thanks for the update @ray-linn. We are re-factoring the installation so that this issue should be avoided in future releases
