### ISSUE TITLE
How to get the Token length in .NET

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/onnxruntime-genai#666]
Quick question I am using the example listed here [LabsPhi301](https://github.com/microsoft/Phi-3CookBook/blob/main/md/07.Labs/Csharp/src/LabsPhi301/Program.cs) and I would like to check the length of the token before submitting it to the SLM. I don't see anywhere where I can get the token length from the Tokenizer. 

Thanks 🙏.

**Comment by baijumeswani** [comment]
Could you elaborate on what you mean by the length of the token?

If you wanted to understand what string each token corresponds to, you could invoke the tokenizer decode function on each token id.

**Comment by MaxAkbar** [comment]
I know that we have large amounts of tokens for the new Phi-3 models but I wanted to trim the history of the chat based on the token limit. This why I need the token length and prior to sending it I can trim it if needed. Hope this helps.

**Comment by MaxAkbar** [comment]
After looking at the examples I think I found how to get the length of tokens:

```
var sequences = await Tokenizer.EncodeAsync(prompt);
var tokenCount = sequences[0].ToArray().Length;
```

**Comment by MaxAkbar** [comment]
An example was found in the Genny.sln.
