### ISSUE TITLE
DLL load failed while importing onnxruntime_genai: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by mingxing0769** [microsoft/onnxruntime-genai#668]
DLL load failed while importing onnxruntime_genai: The Dynamic Link Library (DLL) initialization routine failed.

test.py  code:
```

import os
import sys

def add_dll_directory():
    if sys.platform.startswith("win"):
        cuda_path = os.getenv("CUDA_PATH", None)
        if cuda_path:
            cuda_bin_path = os.path.join(cuda_path, "bin")
            os.add_dll_directory(cuda_bin_path)
            print(f"Added CUDA DLL directory: {cuda_bin_path}")
        else:
            raise ImportError("Could not find the CUDA libraries. Please set the CUDA_PATH environment variable.")
    else:
        print("This function is a no-op on non-Windows platforms.")

add_dll_directory()

try:
    from onnxruntime_genai.onnxruntime_genai import *
except ImportError as e:
    print(f"ImportError: {e}")
    raise e
```
-------------------
Run the results：
```

E:\Python\onnx\env\Scripts\python.exe E:\Python\onnx\env\test.py 
Added CUDA DLL directory: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin
Added CUDA DLL directory: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin
ImportError: DLL load failed while importing onnxruntime_genai: 动态链接库(DLL)初始化例程失败。
Traceback (most recent call last):
  File "E:\Python\onnx\env\lib\site-packages\onnxruntime_genai\__init__.py", line 10, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
ImportError: DLL load failed while importing onnxruntime_genai: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\onnx\env\test.py", line 22, in <module>
    raise e
  File "E:\Python\onnx\env\test.py", line 19, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
  File "E:\Python\onnx\env\lib\site-packages\onnxruntime_genai\__init__.py", line 18, in <module>
    from onnxruntime_genai.onnxruntime_genai import *
ImportError: DLL load failed while importing onnxruntime_genai: 动态链接库(DLL)初始化例程失败。

进程已结束，退出代码为 1
```

pip list:
(env) PS E:\Python\onnx> pip list
Package                Version
---------------------- ------------
bitsandbytes           0.43.1
certifi                2024.6.2
charset-normalizer     3.3.2
fsspec                 2024.6.1
huggingface-hub        0.23.4
idna                   3.7
intel-openmp           2021.4.0
Jinja2                 3.1.3
MarkupSafe             2.1.5
mkl                    2021.4.0
mpmath                 1.3.0
networkx               3.2.1
numpy                  2.0.0
onnxruntime-genai-cuda 0.3.0
packaging              24.1
pillow                 10.2.0
pip                    24.1.1
PyYAML                 6.0.1
regex                  2024.5.15
requests               2.32.3
safetensors            0.4.3
setuptools             68.2.0
sympy                  1.12
tbb                    2021.11.0
tokenizers             0.19.1
torch                  2.3.1+cu121
torchaudio             2.3.1+cu121
torchvision            0.18.1+cu121
tqdm                   4.66.4
transformers           4.40.2
triton                 2.0.0
typing_extensions      4.12.2
urllib3                2.2.2
wheel                  0.41.2

**Comment by baijumeswani** [comment]
`onnxruntime-genai-cuda` is expecting cuda 11.8 and cudnn 8.x (for cuda 11.8).

If you would like to use cuda 12, you can install `onnxruntime-genai-cuda` using. This requires cuda 12.2 and cudnn 9.x for cuda 12.

```
pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ onnxruntime-genai-cuda
```

**Comment by natke** [comment]
Installation instructions here: https://onnxruntime.ai/docs/genai/howto/install#cuda-12

**Comment by mingxing0769** [comment]
After upgrade the C++ runtime for Visual Studio.  it has been successful [(https://onnxruntime.ai/docs/genai/howto/troubleshoot.html)]

**Comment by mingxing0769** [comment]
After upgrade the C++ runtime for Visual Studio. it has been successful (https://onnxruntime.ai/docs/genai/howto/troubleshoot.html)
