### ISSUE TITLE
Fail to build win64 onnxruntime-genai-directml from source

### ISSUE THREAD

**Issue by shane-huang** [microsoft/onnxruntime-genai#676]
Hello team, 

I'm trying to build a Win64 Python wheel from source using [this guide](https://onnxruntime.ai/docs/genai/howto/build-from-source.html). But after the build finishes, I only get a Win32 wheel named `onnxruntime_genai_directml-0.4.0.dev0-cp311-cp311-win32.whl`. What's odd is that the `.pyd` file in `build\Windows\Release\wheel\onnxruntime_genai` looks like it's 64-bit, named `onnxruntime_genai.cp311-win_amd64.pyd`. See full contents in the folder below: 

<img src="https://github.com/microsoft/onnxruntime-genai/assets/1995599/4bf5820e-6d7b-4bff-9fe0-70d01dfe012d" width="50%">

Additional information you may need: 
- Build Env
   - python 3.11 ('64bit', 'WindowsPE')
   - Win11 x64
   - cmake version 3.29.6  
- The build command I used is 
```
python build.py --use_dml --skip_tests --skip_csharp --config Release
```
- For [install-onnx-runtime](https://onnxruntime.ai/docs/genai/howto/build-from-source.html#install-onnx-runtime) part, I tried [option 2 ption 2: Install from nightly](https://onnxruntime.ai/docs/genai/howto/build-from-source.html#option-2-install-from-nightly) as well as [option 3: building from source](https://onnxruntime.ai/docs/genai/howto/build-from-source.html#option-3-build-from-source). Both result in obtaining the Win32 wheel. 

Could you please kindly guide me on how to correctly build a Win64 python wheel?

**Comment by natke** [comment]
Hi @shane-huang, that is indeed strange. Are you using a virtual python environment? If so, which one? venv or conda or something different?

Can you list the packages in your python environment?

And can you attach the entire build output from the `python build.py` command that you run?

**Comment by baijumeswani** [comment]
Could you please paste the output of this command from your terminal?

```
where cl.exe
```

For me, it gives the following:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>where cl.exe
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe
```

Notice the x64 in the path to cl.exe. If your console gives you x86 in the path, it would indicate that you're using the incorrect cl.exe to compile the program.

Try using a x64 console (maybe search for `x64 Native Tools Command Prompt` in windows and use that console for compilation).

**Comment by shane-huang** [comment]
I am using Developer Powershell for VS 2022 for building (Community version).

I tried executing `cl.exe` and got the message saying it's for **x86**. And I  found my x64 compiler at location "`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\c1.exe`" - when executing it I got the message saying it's for **x64**.  So it does seem I'm using 32 bit compiler as default. 

Then I stuck at changing the the default compiler in Powershell from x86 to x64. I tried: 

1. add the x64 cl.exe path to the front of the system Path variable and restart the Powershell, it does not work. 
2. use `& "'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64` and `" & 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat'"`. Both give me the message `[vcvarsall.bat] Environment initialized for: 'x64'`. But when executing cl.exe. It still says for "x86".

**Comment by baijumeswani** [comment]
Can you open this console and build from there?

x64 Native Tools Command Prompt for VS 2022

![image](https://github.com/microsoft/onnxruntime-genai/assets/12852605/d3b15deb-60f6-4e5d-986c-371ae87a62b4)

**Comment by shane-huang** [comment]
Yes I have found this command prompt and checked it does use x64 cl.exe. I will try building my wheel with it.

**Comment by baijumeswani** [comment]
@shane-huang hope the above worked for you. Will close this issue now. Please let us know if that didn't help.
