### ISSUE TITLE
Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException with Phi-3 

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/onnxruntime-genai#684]
Hi Team

I am not able to load the model which I downloaded from here: https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx/tree/main

The error which I am getting is:

`Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: 'Load model from D:\models\Phi-3-mini-4k-instruct-onnx\cpu_and_mobile\cpu-int4-rtn-block-32\phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx failed:Protobuf parsing failed.'`

**Comment by kunal-vaishnavi** [comment]
Can you share the steps you took to download? Are you following the [Phi-3 tutorial](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi-3-tutorial.md)?

The ONNX models are uploaded using `git lfs` to manage large file storage. If you do not have `git lfs` installed locally, the ONNX models won't download and the protobuf parsing error will occur.

**Comment by arafattehsin** [comment]
Thanks @kunal-vaishnavi for the response. I am definitely following the Phi-3 tutorial and I ran this: 

![image](https://github.com/microsoft/onnxruntime-genai/assets/16351038/6cb9e0fb-9547-4334-93a1-bdd6a276e166)

**Comment by natke** [comment]
Hi @arafattehsin, can you please list the files and their sizes that you have in D:\models\Phi-3-mini-4k-instruct-onnx\cpu_and_mobile\cpu-int4-rtn-block-32?

**Comment by arafattehsin** [comment]
@natke This gave me an idea to use huggingface-cli instead of git and turned out that I was able to make it work. It was the poor performance of `git clone` vs. `huggingface cli`. 

I'd like to close it now.
