### ISSUE TITLE
[Documentation] phi-3 vision tutorial lacks samples for languages that are actually used for desktop development.

### ISSUE THREAD

**Issue by BrainSlugs83** [microsoft/onnxruntime-genai#690]
### Describe the documentation issue

All of the samples appear to be in Python.  Nothing in C, or C#.

Python is awesome for academia, but most Windows desktop App developers are developing desktop and enterprise apps in modern languages like C#, and sometimes in C, it seems kind of frustrating that there is no examples on how to consume these models in a modern desktop app.

Please develop and share desktop app examples that use the Phi-3-vision model showcasing C# and other modern desktop app development stacks that windows developers are using today.

### Page / URL

https://onnxruntime.ai/docs/genai/tutorials/

**Comment by baijumeswani** [comment]
Please see the [C# example](https://github.com/microsoft/onnxruntime-genai/tree/main/examples/csharp/HelloPhi3V) and the [C/C++ example](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/c/src/phi3v.cpp) for phi3-vision.

**Comment by baijumeswani** [comment]
I'll close this issue since we have examples for phi3 vision for c++ and c#. Please let us know if those examples do not work for you or if you think we should add more documentation for easier discoverability.
