### ISSUE TITLE
[Feature request] Support for LLama3.1

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [microsoft/onnxruntime-genai#721]
Llama 3.1 has been released, and it includes a small change in the model's forward part that makes the current version of ONNX unable to run it.

I'm a member of [homebrew/jan](https://github.com/janhq). Currently, we support the Llama 3 model, and now I'm planning to update the model execution part of ONNX to support Llama 3.1 for integration into our project at [cortex.onnx](https://github.com/janhq/cortex.onnx).

**Comment by kunal-vaishnavi** [comment]
The PR to support LLaMA 3.1 can be found [here](https://github.com/microsoft/onnxruntime-genai/pull/750). Once merged, you can use the ["from source"](https://github.com/microsoft/onnxruntime-genai/blob/main/src/python/py/models/README.md) commands for the model builder to build your desired ONNX model.
