### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't byte 0xb2 in position 175: invalid start byte

### ISSUE THREAD

**Issue by camike** [microsoft/onnxruntime-genai#725]
**Describe the bug**
When I run a model with DML Execution Provider that converted from openbmb/MiniCPM-2B-sft-fp32-llama-format using builder.py, i got an error like this:
```  
  generator.compute_logits()
UnicodeDecodeError: 'utf-8' codec can't byte 0xb2 in position 175: invalid start byte
```
 
**To Reproduce**
I positioned the issue code.
 ```
ComPtr<IDMLCompiledOperator> CreateCastOperator(
    IDMLDevice* dml_device,
    uint32_t num_elements,
    DML_TENSOR_DATA_TYPE source_data_type,
    DML_TENSOR_DATA_TYPE target_data_type) {
  // Create the input tensor desc
  DML_BUFFER_TENSOR_DESC input_buffer_desc{};
  input_buffer_desc.Sizes = &num_elements;
  input_buffer_desc.DimensionCount = 1;
  input_buffer_desc.DataType = source_data_type;
  input_buffer_desc.TotalTensorSizeInBytes = num_elements * DataTypeSizeInBytes(source_data_type);
  DML_TENSOR_DESC input_tensor_desc = {DML_TENSOR_TYPE_BUFFER, &input_buffer_desc};

  // Create the output tensor desc
  DML_BUFFER_TENSOR_DESC output_buffer_desc{};
  output_buffer_desc.Sizes = &num_elements;
  output_buffer_desc.DimensionCount = 1;
  output_buffer_desc.DataType = target_data_type;
  output_buffer_desc.TotalTensorSizeInBytes = num_elements * DataTypeSizeInBytes(target_data_type);
  DML_TENSOR_DESC output_tensor_desc = {DML_TENSOR_TYPE_BUFFER, &output_buffer_desc};

  DML_CAST_OPERATOR_DESC cast_op_desc{};
  cast_op_desc.InputTensor = &input_tensor_desc;
  cast_op_desc.OutputTensor = &output_tensor_desc;
  DML_OPERATOR_DESC cast_op_dml_desc = {DML_OPERATOR_CAST, &cast_op_desc};
  ComPtr<IDMLOperator> cast_op;

  THROW_IF_FAILED(dml_device->CreateOperator(&cast_op_dml_desc, IID_PPV_ARGS(&cast_op)));
  ComPtr<IDMLCompiledOperator> compiled_cast_op;

  THROW_IF_FAILED(dml_device->CompileOperator(cast_op.Get(), DML_EXECUTION_FLAG_DESCRIPTORS_VOLATILE, IID_PPV_ARGS(&compiled_cast_op)));
  return compiled_cast_op;
}
```
***Variables***
num_elements:   122753
source_data_type:  ONNX_TENSOR_TYPE_FLOAT16
target_data_type:  ONNX_TENSOR_TYPE_FLOAT32

***Error***
The CreateOperator method return ***Invalid Arguments***

***My Action***
According to this document, [https://learn.microsoft.com/en-us/windows/ai/directml/dml-helper-functions#dmlcalcbuffertensorsize](https://learn.microsoft.com/en-us/windows/ai/directml/dml-helper-functions#dmlcalcbuffertensorsize)
DirectML requires that all bound buffers must have a total size that is DWORD-aligned, and hence the minimum implied size in bytes must be rounded up to the nearest 4-byte boundary.

I aligned `input_buffer_desc.TotalTensorSizeInBytes`'s value from `122753*2`  to `122753*2+2`, then it is ok, and I have to aligned the input tensor size when the `compiled_cast_op`  is called.

**Expected behavior**
`122753` is vocab_size of minicpm model, doesn't like phi3 model whose vocab_size is `32064`, it is an odd instead of even, so this method doesn't work when ConvertFp16ToFp32 ?   Is there a way to fixed this issue?

**Comment by skyline75489** [comment]
Thanks for the feedback!

**Comment by baijumeswani** [comment]
[camike](https://github.com/camike) would you like to propose the solution in a PR?

cc @PatriceVignola

**Comment by camike** [comment]
I have a local commit that fixed this issue, but I don't have a permission to create new PR. @PatriceVignola

**Comment by skyline75489** [comment]
@camike you can fork this repo and push in your own fork, then create the PR.

**Comment by camike** [comment]
See [https://github.com/microsoft/onnxruntime-genai/pull/773](https://github.com/microsoft/onnxruntime-genai/pull/773) @skyline75489 @baijumeswani

**Comment by abdelaziz-jaddi** [comment]
For me, when I run a model with the DML Execution Provider, specifically the model Phi-3-mini-128k-instruct-onnx/directml/directml-int4-awq-block-128, I get the following error:

```
generator.compute_logits()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 195: invalid continuation byte
```

I would like to know if other users have encountered this error, or if there is a workaround for it.

Thank you in advance for any help or suggestions.

**Comment by natke** [comment]
Which version of onnxruntime-genai are you using?
