### ISSUE TITLE
Can we run phi-3 vision on mobile

### ISSUE THREAD

**Issue by surajat17** [microsoft/onnxruntime-genai#726]
Just like that title says, can we use microsoft/Phi-3-vision-128k-instruct-onnx-cpu to run on mobile in similar way we are running https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx?

**Comment by baijumeswani** [comment]
Yes, we have an example to show that: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/phi-3. This should be good to get started.

There is even more work going on for the Java and Objective-C bindings. You can refer changes proposed in this PR: https://github.com/microsoft/onnxruntime-inference-examples/pull/449

Will close this issue. Please feel free to ask follow-up questions.
