### ISSUE TITLE
Converting GGUF Q4 Model to ONNX Format

### ISSUE THREAD

**Issue by Narendra-Singh-shekhawat** [microsoft/onnxruntime-genai#761]
Dear Team,

I am currently attempting to convert a GGUF Q4 model to ONNX format using the onnxruntime-genai tool, but I am encountering the following error:
Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:957: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 722, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 825, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 141: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 2376, in <module>
    create_model(args.model_name, args.input, args.output, args.precision, args.execution_provider, args.cache_dir, **extra_options)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/onnxruntime_genai/models/builder.py", line 2234, in create_model
    config = AutoConfig.from_pretrained(hf_name, use_auth_token=True, trust_remote_code=True, **extra_kwargs)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 972, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 726, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf' is not a valid JSON file.

It seems like the onnxruntime-genai tool is trying to read a configuration file from the provided GGUF model, which is not in JSON format. I would like to know if onnxruntime-genai supports GGUF model conversion, or if there is an alternative approach to achieve this.

Here is the command I am using for the conversion:                                                                                                                                    

python3 -m onnxruntime_genai.models.builder \
    -m /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf \
    -i /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf \
    -o /home/ubuntu/onnx/output \
    -p fp32 \
    -e cpu \
    -c /home/ubuntu/onnx/cache
Your assistance in resolving this issue would be greatly appreciated.

**Comment by kunal-vaishnavi** [comment]
> It seems like the onnxruntime-genai tool is trying to read a configuration file from the provided GGUF model, which is not in JSON format. I would like to know if onnxruntime-genai supports GGUF model conversion, or if there is an alternative approach to achieve this.

Currently, ONNX Runtime GenAI's model builder only supports [converting float16/float32 GGUF models](https://github.com/microsoft/onnxruntime-genai/blob/main/src/python/py/models/README.md#gguf-model) and not already-quantized GGUF files. If you have the original float16/float32 weights in a GGUF file, you can try using that to get the ONNX model.

> Here is the command I am using for the conversion:
> 
> python3 -m onnxruntime_genai.models.builder
> -m /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf
> -i /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf
> -o /home/ubuntu/onnx/output
> -p fp32
> -e cpu
> -c /home/ubuntu/onnx/cache

For your command, you should specify the model's original name in Hugging Face for the `-m` flag so that the `config.json` and associated tokenizer JSON files needed for ONNX Runtime GenAI can be downloaded. For instance, it appears you are using the [SeaLLM-7B-v2](https://huggingface.co/SeaLLMs/SeaLLM-7B-v2) model. You should change `-m /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf` to `-m SeaLLMs/SeaLLM-7B-v2` instead. You can also quantize the resulting ONNX model to INT4 precision by using `-p int4` instead.

**Comment by Narendra-Singh-shekhawat** [comment]
Hi Kunal,

Thank you for your prompt response. Following your advice, I updated the commands but encountered the following error:

(venv) root@ip-172-31-29-246:/home/ubuntu/onnx# python3 builder.py \
    -m SeaLLMs/SeaLLM-7B-v2 \
    -i /home/ubuntu/onnx/models/SeaLLM-7B-v2.q4_0.gguf \
    -o /home/ubuntu/onnx/output \
    -p int4 \
    -e cpu

Valid precision + execution provider combinations are: FP32 CPU, FP32 CUDA, FP16 CUDA, FP16 DML, INT4 CPU, INT4 CUDA, INT4 DML
Extra options: {}
/home/ubuntu/onnx/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:957: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
GroupQueryAttention (GQA) is used in this model.
Traceback (most recent call last):
  File "/home/ubuntu/onnx/builder.py", line 2575, in <module>
    create_model(args.model_name, args.input, args.output, args.precision, args.execution_provider, args.cache_dir, **extra_options)
  File "/home/ubuntu/onnx/builder.py", line 2468, in create_model
    onnx_model.make_model(input_path)
  File "/home/ubuntu/onnx/builder.py", line 1567, in make_model
    model = GGUFModel.from_pretrained(self.model_type, input_path, self.head_size, self.hidden_size, self.intermediate_size, self.num_attn_heads, self.num_kv_heads, self.vocab_size)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/onnxruntime_genai/models/gguf_model.py", line 244, in from_pretrained
    model = GGUFModel(input_path, head_size, hidden_size, intermediate_size, num_attn_heads, num_kv_heads, vocab_size)
  File "/home/ubuntu/onnx/venv/lib/python3.10/site-packages/onnxruntime_genai/models/gguf_model.py", line 131, in __init__
    module.self_attn.k_proj.weight.tensor = tensor.data.reshape(k_shape)
ValueError: cannot reshape array of size 2359296 into shape (1024,4096)

**Comment by kunal-vaishnavi** [comment]
As mentioned above, currently ONNX Runtime GenAI's model builder only supports [converting float16/float32 GGUF models](https://github.com/microsoft/onnxruntime-genai/blob/main/src/python/py/models/README.md#gguf-model) and not already-quantized GGUF models. Your `SeaLLM-7B-v2.q4_0.gguf` file is already quantized to 4-bits so it is not currently supported.

If you have the original float16/float32 weights for `SeaLLM-7B-v2` in a GGUF file, you can try using that to get the ONNX model. Alternatively, you can build the ONNX model from the original PyTorch weights and still quantize to 4-bits. Here's an example for that.

```bash
# Option 1: from wheel
$ python3 -m onnxruntime_genai.models.builder -m SeaLLMs/SeaLLM-7B-v2 -o /home/ubuntu/onnx/output -p int4 -e cpu -c /home/ubuntu/onnx/cache

# Option 2: from source
$ python3 builder.py -m SeaLLMs/SeaLLM-7B-v2 -o /home/ubuntu/onnx/output -p int4 -e cpu -c /home/ubuntu/onnx/cache
```

**Comment by Narendra-Singh-shekhawat** [comment]
hi kunal,
Thank you for your prompt response,
After your suggestion i have implemented 
getting this error : [Onnx, Error: Failed to load model because protobuf parsing failed](https://discuss.huggingface.co/t/onnx-error-failed-to-load-model-because-protobuf-parsing-failed/95511)

**Comment by kunal-vaishnavi** [comment]
This error can happen when you provide a path to a folder instead of a path to an ONNX model. This could be either because of a bug in your code or a bug with how you are running your code. Can you share the following information to reproduce the error?

1. The code that you tried that gets you this error and how you run your code
2. The traceback with the error message. [For example](https://realpython.com/python-traceback/):
```
$ python example.py
Traceback (most recent call last):
  File "/path/to/example.py", line 4, in <module>
    greet('Chad')
  File "/path/to/example.py", line 2, in greet
    print('Hello, ' + someon)
NameError: name 'someon' is not defined
```
3. The package versions you are using

**Comment by natke** [comment]
Hi @Narendra-Singh-shekhawat, can you provide the above information for us to help you with your issue?

**Comment by natke** [comment]
Closed due to inactivity. Please re-open with the information requested if needed

**Comment by NEWbie0709** [comment]
Hi, I would like to test converting a GGUF model to ONNX. Could you provide an example and explain the steps to convert it?

**Comment by EigenOz** [comment]
Hi @natke @kunal-vaishnavi  , can you please share an example to convert GGUF model to ONNX ?

**Comment by EigenOz** [comment]
I was able to run it successfully for tiny-random-LlamaForCausalLM-GGUF . 

Thanks :)
