### ISSUE TITLE
count of tokens 

### ISSUE THREAD

**Issue by janjanusek** [microsoft/onnxruntime-genai#781]
Hello,
when I build big prompt I always have to estimate roughly how many tokes it contains, is there a exact way how can I calculate this number for phi3 intruct model in C#?

**Comment by janjanusek** [comment]
btw I saw ticket https://github.com/microsoft/onnxruntime-genai/issues/666 but I'm looking for something where I could dynamically push words or build string like with string builder and see how many tokens promt have so far.

**Comment by RyanUnderhill** [comment]
Unfortunately text->tokens has a "many to many" mapping and is best done in the largest blocks known, like all/paragraph/sentence. Doing it by word can possibly give different results, as multiple words could map to one token.

You can safely tokenize one sentence at a time into a buffer and then append the buffers together if they're under your token limit (or do it by paragraph). I'm not a C# expert so let us know if our current API makes that really ugly to do.
