### ISSUE TITLE
[IGNORE] New issue labeler policy test - CUDA TensorRT

### ISSUE THREAD

**Issue by sophies927** [microsoft/onnxruntime-genai#788]
**Describe the bug**
Please ignore this issue - I am testing the new issue labeler and would like to see if the appropriate labels are applied.

DirectML

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by natke** [comment]
Comment
