### ISSUE TITLE
Unable to implement onnxruntime_genai in Android project

### ISSUE THREAD

**Issue by Dave86ch** [microsoft/onnxruntime-genai#806]
Environment
Android Studio
Gradle
Target SDK: 34
Min SDK: 28

Issue
Failed to resolve: 
```com.microsoft.onnxruntime:onnxruntime_genai-android:latest.release```
Working Configuration
gradle
```implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'```
This imports correctly.
Attempted for GenAI
gradle
```implementation 'com.microsoft.onnxruntime:onnxruntime-genai:0.3.0'```
This fails to resolve.

Questions
Is onnxruntime_genai available for Android?
If yes, what's the correct implementation string?
Are there specific version requirements or additional setup steps?
How does the implementation differ from the standard onnxruntime-android?

**Comment by krishna15898** [comment]
Hey @Dave86ch I am facing the same issue, could ou please share how you resolved this?
