### ISSUE TITLE
Freezes while loading model.

### ISSUE THREAD

**Issue by elephantpanda** [microsoft/onnxruntime-genai#817]
In c# the line `model=Model("[model path"]) ` freezes until the model is loaded.

Can I suggest having a LoadModelAsync function to load the model in the background so I can display a loading screen? (I am using Unity and c#)

Never mind, I have managed to do it by running this in a Task. It seems to work.

The same with:

`generator.ComputeLogits();
        generator.GenerateNextToken();`

I also run those in a Task and it seems to work OK. But I'm not sure if this is the correct way to do things.

**Comment by RyanUnderhill** [comment]
Yep, that's the correct way. As we use onnxruntime to load models, it has no asynchronous way to load them, so you did the best thing which is to put it in a background thread.
