### ISSUE TITLE
Some answers in phi3-vision just return </s>

### ISSUE THREAD

**Issue by elephantpanda** [microsoft/onnxruntime-genai#823]
In [phi-3 vision directml](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx-directml) using either python or c# certain questions just return `</s>`

For example "Why is the sky blue?" returns a complete answer but "What is the capital of France?" consistently returns just` </s>` (i.e. it returns blank).

Not sure this is a bug specifically with genai but it may be a bug with the model itself. Either way, is there a suggested way to combat this? And has anyone else noticed this?

Perhaps genai needs to be fixed so that it doesn't generate the "STOP" token as it's first token! (Also it shouldn't be writing the stop token to the screen)

**Comment by elephantpanda** [comment]
I have noticed it works better if I leave out the newline characters `\n` from the prompt. Was the vision model trained with these newline characters?

**Comment by elephantpanda** [comment]
(Same things happen in version 0.4.0) And there is no way to tell it to ignore this token and pick a different one. There needs to be a way to allow us to have more control on which tokens we choose from the distribution.

**Comment by kunal-vaishnavi** [comment]
The original `config.json` in the [Phi-3 vision repo](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct) says that the [EOS token id is 2](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct/blob/c45209e90a4c4f7d16b2e9d48503c7f3e83623ed/config.json#L19). However, it appears that the actual [EOS token id is 32007](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct/blob/c45209e90a4c4f7d16b2e9d48503c7f3e83623ed/tokenizer_config.json#L85). I updated the published `genai_config.json` files in Hugging Face for Phi-3 vision to fix this.

You can also update your `genai_config.json` file locally by changing
```
"eos_token_id": [
    2,
    32000,
    32001,
    32007
]
```
to
```
"eos_token_id": 32007
```

**Comment by natke** [comment]
@elephantpanda did you still see the issue when you update the EOS token?

**Comment by elephantpanda** [comment]
> @elephantpanda did you still see the issue when you update the EOS token?

Yes, still seems to end without an answer for certain inputs. Although my bigger problem with the vision model is it is crashing for me when trying to give it an image. But I think I narrowed that problem down with [more details here](https://github.com/microsoft/onnxruntime/issues/21869).

**Comment by natke** [comment]
@elephantpanda Did you happen to try this on CPU?

**Comment by elephantpanda** [comment]
It's the same on GPU and CPU. If I don't include a newline character after "<|assistant|>" in the prompt, that seems to fix it as far as I can tell. I'll keep trying to see if this really does fix it.

**Comment by kunal-vaishnavi** [comment]
The new [Phi-3 vision](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct-onnx) and [Phi-3.5 vision](https://huggingface.co/microsoft/Phi-3.5-vision-instruct-onnx) ONNX models have now been released. The new models support no-image, single-image, and multi-image scenarios.
