### ISSUE TITLE
Spelling errors in rel-0.4.0

### ISSUE THREAD

**Issue by belovedxixi** [microsoft/onnxruntime-genai#826]
![397f2056-d134-47ff-80ac-660fbccb86d8](https://github.com/user-attachments/assets/3f6de7c3-09d1-4347-88c6-781b2a47d43e)
In https://github.com/microsoft/onnxruntime-genai/blob/rel-0.4.0/src/python/py/models/quantized_model.py, there is a spelling mistake in line 490.

**Comment by ajindal1** [comment]
Thanks, fixed in https://github.com/microsoft/onnxruntime-genai/pull/801
