### ISSUE TITLE
Documentation missing for "custom scoring"

### ISSUE THREAD

**Issue by elephantpanda** [microsoft/onnxruntime-genai#840]
In the [documentation page](https://onnxruntime.ai/docs/genai/) it says "You can also easily add custom scoring". 

My understanding is this is a way to make a custom way to pick tokens from the probability values? 

But I could not find any further documentation on this. Is this implemented yet. And is that what "custom scoring" means?

(I am using c# but I cuoldn't find any documentation for custom scoring in any of the languages).

Thanks.

**Comment by natke** [comment]
Thanks for raising this @elephantpanda! We will add an example of how to do this

**Comment by elephantpanda** [comment]
Thanks. BTW, as I mentioned in a different post, I would really like to be able to specify a completely custom function for choosing the token from the probability values, not just select from the options in the config file. But having the options in the config file is good too.

**Comment by RyanUnderhill** [comment]
Ah, my early promises that haven't been implemented yet. I think this conversation covers the important part: https://github.com/microsoft/onnxruntime/issues/21847

**Comment by natke** [comment]
Closing this one as the relevant discussion is in https://github.com/microsoft/onnxruntime/issues/21847
