### ISSUE TITLE
Non-zero status code returned while running DmlFusedNode_0_0 node

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/onnxruntime-genai#863]
**Describe the bug**

Using [directml-int4-awq-block-128](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx/tree/main/directml/directml-int4-awq-block-128) with the [Phi3-Cookbook Lab 301](https://github.com/microsoft/Phi-3CookBook/blob/main/md/07.Labs/Csharp/src/LabsPhi301/Program.cs) results in:

```
2024-09-03 00:31:24.8733206 [E:onnxruntime:onnxruntime-genai, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\execution_frame.cc:173 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,32,46,96} Requested shape:{1,32,2048,96}

Unhandled exception. Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\execution_frame.cc:173 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,32,46,96} Requested shape:{1,32,2048,96}

   at Microsoft.ML.OnnxRuntimeGenAI.Generator.ComputeLogits()
   at Program.<Main>$(String[] args) in D:\labsphi301\Program.cs:line 37
```

![image](https://github.com/user-attachments/assets/19c095a5-451e-44e4-a588-6a14c9c03c9a)

**To Reproduce**
1. Clone Phi-3-mini-4k-instruct-onnx
2. Clone Phi3 Cookbook
3. Update LabPhi301 dependencies to current versions of the runtime and GenAI
4. Add runtime settings as described in #862 
5. Application runs but fails with above error after first word of Phi3's response

**Expected behavior**

Phi3 would answner. 

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11
- .NET 8.0
- [onnxruntime-genai](https://github.com/microsoft/onnxruntime-genai) 0.4.0
- onnxruntime 1.19.1

**Additional context**

labsphi301.csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.19.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" Version="0.4.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.4.0" />
  </ItemGroup>

</Project>
```

Program.cs:
```
using Microsoft.ML.OnnxRuntimeGenAI;

var modelPath = @"D:\Phi-3-mini-4k-instruct-onnx\directml-int4-awq-block-128";
var model = new Model(modelPath);
var tokenizer = new Tokenizer(model);

var systemPrompt = "You are an AI assistant that helps people find information. Answer questions using a direct style. Do not share more information that the requested by the users.";

// chat start
Console.WriteLine(@"Ask your question. Type an empty string to Exit.");

// chat loop
while (true)
{
    // Get user question
    Console.WriteLine();
    Console.Write(@"Q: ");
    var userQ = Console.ReadLine();    
    if (string.IsNullOrEmpty(userQ))
    {
        break;
    }

    // show phi3 response
    Console.Write("Phi3: ");
    var fullPrompt = $"<|system|>{systemPrompt}<|end|><|user|>{userQ}<|end|><|assistant|>";
    var tokens = tokenizer.Encode(fullPrompt);

    var generatorParams = new GeneratorParams(model);
    generatorParams.SetSearchOption("max_length", 2048);
    generatorParams.SetSearchOption("past_present_share_buffer", false);
    generatorParams.SetInputSequences(tokens);

    var generator = new Generator(model, generatorParams);
    while (!generator.IsDone())
    {
        generator.ComputeLogits();
        generator.GenerateNextToken();
        var outputTokens = generator.GetSequence(0);
        var newToken = outputTokens.Slice(outputTokens.Length - 1, 1);
        var output = tokenizer.Decode(newToken);
        Console.Write(output);
    }
    Console.WriteLine();
}
```

**Comment by sirredbeard** [comment]
I can reproduce this on a Mistral family model converted with `onnxruntime_genai.models.builder`, specifically:

`python3 -m onnxruntime_genai.models.builder -m "ajibawa-2023/Code-Mistral-7B" -o ajibawa-2023-Code-Mistral-7B-onnx-directml-int4 -p int4 -e dml -c cache`

Error:

``
The2024-09-04 17:13:52.9463562 [E:onnxruntime:onnxruntime-genai, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\execution_frame.cc:173 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,8,147,128} Requested shape:{1,8,200,128}

Unhandled Exception: Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\execution_frame.cc:173 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,8,147,128} Requested shape:{1,8,200,128}

   at Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(IntPtr) + 0x54
   at Program.<Main>$(String[] args) + 0x994
   at pengwin-terminal-assistant!<BaseAddress>+0xdf650
```

**Comment by yufenglee** [comment]
@sirredbeard, you need to set the past_present_share_buffer to True for DML. Will add an error check for this.

[past_present_share_buffer](https://github.com/microsoft/Phi-3CookBook/blob/9780b516c3fd7fd2ae19a32eca368cc5fb2a9769/md/07.Labs/Csharp/src/LabsPhi301/Program.cs#L57)

**Comment by natke** [comment]
@sirredbeard closing this issue for now. Your issue should be resolved by setting `past_present_share_buffer` to `true`.

**Comment by rasteiner** [comment]
For people finding this from Google.
In my case I resolved this issue by changing the build platform from "Any CPU" to "x64". Maybe this helps someone.

**Comment by jiaxuwu2021** [comment]
onnxruntime-genai 0.5.2
the way changing from "Any CPU" to "x64" can solve my "Debug" version (--configure Debug) 
but "Release" version (--configuration Release) still failed with this error message:
`2024-12-03 11:42:49.8622852 [E:onnxruntime:onnxruntime-genai, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(1066)\onnxruntime.dll!00007FF82D9A2821: (caller: 00007FF82DA35159) Exception(2) tid(6f68) 887A0001 The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.`
`Enable the D3D debug layer in order to see details via debug messages.`
