### ISSUE TITLE
Bug in calculating CPU memory (RAM?) in benchmark_e2e python script

### ISSUE THREAD

**Issue by jakubedzior** [microsoft/onnxruntime-genai#887]
**Describe the bug**
The current logic behind calculating peak used memory in [benchmark/python/benchmark_e2e.py L62-L64](https://github.com/microsoft/onnxruntime-genai/blob/39a0da19cb6a042218a604609b3f680dfc53440a/benchmark/python/benchmark_e2e.py#L62-L64) is, I believe, incorrect, as, like in the function `monitor_gpu_memory` above, it should be comparing both values in GBs before taking the max. As of currently, the `current_used_memory` is in bytes, as returned by `psutil.virtual_memory().used`, which makes it always bigger numerically than `peak_cpu_memory`, which is already converted to GBs at this step.

The result of this is `peak_cpu_memory` is always just the last measurement made, which makes `--print_memory_usage` unusable and `peak_cpu_memory(GiB)` value in benchmark record result file incorrect.

**Expected behavior**
```python
current_used_memory = round(psutil.virtual_memory().used / 1024**3, 2)
with peak_memory_lock:
    peak_cpu_memory = max(peak_cpu_memory, current_used_memory)
```

PS: I'm unsure if that's this repo's policy or my company's but I'm unable to open a pull request, so I've opened this bug instead.

**Comment by baijumeswani** [comment]
Thanks for reporting this. The logic indeed seems incorrect there.

> PS: I'm unsure if that's this repo's policy or my company's but I'm unable to open a pull request, so I've opened this bug instead.

Could you please fork the repo and create a pull-request from there to main on `microsoft/onnxruntime-genai`?

**Comment by jakubedzior** [comment]
> Could you please fork the repo and create a pull-request from there to main on `microsoft/onnxruntime-genai`?

I did try that, but I guess I can try via my personal account
