### ISSUE TITLE
what is intended purpose of ort_genai.h?

### ISSUE THREAD

**Issue by alando46** [microsoft/onnxruntime-genai#889]
Given we have all of the other cpp header files, what is the purpose of ort_genai.h? Why is the cpp wrapper around C necessary if we have the cpp header files available to use directly?

Just curious to learn more, 8 years swd experience but only a year on cpp. Thanks in advance for any insight! Loving the project.

**Comment by baijumeswani** [comment]
C interfaces maintain ABI compatibility across various compilers and platforms, which is crucial when dynamically linking to `onnxruntime-genai`. This compatibility is provided through the C API exposed in `ort_genai_c.h`.

The `ort_genai.h` file is a straightforward C++ wrapper around the C API, designed to offer a more user-friendly interface for interacting with `onnxruntime-genai`.

**Comment by baijumeswani** [comment]
Happy to answer more questions around the C/C++ API in onnxruntime-genai. Closing the issue now.

**Comment by alando46** [comment]
I see, thanks for clarifying @baijumeswani! One follow-on question: Is it possible to do batch inference with the ort_genai.h interface?

```
#include <ort_genai.h>
(and other non-ort includes)

model = OgaModel::Create("C:/pathtomymodel/Phi-3-mini-4k-instruct-onnx/directml/directml-int4-awq-block-128");
tokenizer = OgaTokenizer::Create(*model);
std::unique_ptr<OgaSequences> sequences = OgaSequences::Create();
tokenizer->Encode("A great recipe for Kung Pao chicken is ", *sequences);
auto params = OgaGeneratorParams::Create(*model);
params->SetSearchOption("max_length", 200);
std::unique_ptr<OgaSequences> output_sequences = model->Generate(*params);
```
the above works for for me so long as I only encode a single sequence, although really it would be great to be able to encode multiple sequences (gpu-memory permitting). I'm thinking this must be possible because i see https://github.com/microsoft/onnxruntime-genai/blob/main/src/models/model.h#L74. If I add a second encoding (`tokenizer->Encode("A great recipe for spaghetti meatballs is ", *sequences);`) i get an error at runtime:
```
Exception caught: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(1066)\onnxruntime.dll!0000022B87EBFE31: (caller: 0000022B87F50129) Exception(2) tid(a2bc) 887A0005 The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
```
am I using the api defined in ort_genai.h incorrectly? if this seems like a bug i'd be happy to open an actual bug issue. Thanks in advance for any suggestions!
