### ISSUE TITLE
Does GenAI support a JavaScript based API or React Native?

### ISSUE THREAD

**Issue by ivberg** [microsoft/onnxruntime-genai#895]
**Describe the question**
Does GenAI support a JavaScript based API?

It seems to fully use Phi3 SLM that GenAI or some other calling wrapper is probably needed. However, on [main page](https://github.com/microsoft/onnxruntime-genai) JS is not mentioned, nor is upcoming.

Ultimately, we were hoping to get Phi 3 model to work with GenAI in Reactive Native.
See 
https://onnxruntime.ai/docs/get-started/with-javascript/react-native.html
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/React_Native/ort-rn-basic-usage

Please help clarify or explain the support

**Expected behavior**
A JavaScript, TypeScript, and React Native API is supported for GenAI

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows, iOS & Android
 - Browser - N/A
 - Version latest

**Smartphone (please complete the following information):**
Android & iOS. Don't have specific versions or phones , but expect reasonable versions

**Comment by aciddelgado** [comment]
GenAI does not currently support a Javascript/React Native API but OnnxRuntime does. We will consider adding this in the future. Thank you!
