### ISSUE TITLE
Conflict Between `onnxruntime-genai-directml` and `onnxruntime-qnn` Removes `DMLExecutionProvider` and Lack of NPU Support on Surface Pro 11

### ISSUE THREAD

**Issue by ac1982** [microsoft/onnxruntime-genai#904]
### **Describe the bug**
When installing `onnxruntime-qnn` after having previously installed `onnxruntime-genai-directml`, the `DMLExecutionProvider` is no longer available. After switching to `QNNExecutionProvider`, the application throws an error: `onnxruntime_genai.onnxruntime_genai.OrtException: Specified provider is not supported.` This prevents the model from running with `DirectML`, and without `DMLExecutionProvider`, it defaults to `CPUExecutionProvider`, which leads to significantly reduced performance.

Additionally, the current support only utilizes the GPU on devices such as the Surface Pro 11 with DirectML, but does not leverage the NPU hardware, which could provide better performance for AI workloads.

### **To Reproduce**
1. Install `onnxruntime-genai-directml` using:
   ```
   pip install onnxruntime-genai-directml
   ```
2. Check available providers using `ort.get_available_providers()`; this should return:
   ```
   ['DMLExecutionProvider', 'CPUExecutionProvider']
   ```
3. Install `onnxruntime-qnn`:
   ```
   pip install onnxruntime-qnn
   ```
4. Check available providers again:
   ```
   ['QNNExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
   ```
5. Run the `phi3-qa.py` script using the `QNNExecutionProvider` (or after modifying `genai_config.json` to remove providers):
   ```
   python phi3-qa.py -m directml\directml-int4-awq-block-128
   ```
6. See error: `onnxruntime_genai.onnxruntime_genai.OrtException: Specified provider is not supported`.

### **Expected behavior**
Both `DMLExecutionProvider` and `QNNExecutionProvider` should be available without conflicts, allowing the model to run with either `DirectML` for GPU acceleration or `QNN` for Qualcomm hardware.

Furthermore, there should be native support for NPUs in ONNX Runtime GenAI to fully leverage the capabilities of hardware like the Surface Pro 11, which comes with an NPU for AI acceleration. This would enable much faster inference on devices that include NPUs, rather than defaulting to just CPU or GPU.

### **Desktop:**
- OS: Windows 11 / Surface Pro 11
- ONNX Runtime version: `onnxruntime-genai-directml` and `onnxruntime-qnn`
- Python version: 3.12

### **Additional context**
- When using `DirectML`, everything works fine, and both `DMLExecutionProvider` and `CPUExecutionProvider` are available.
- After installing `onnxruntime-qnn`, the `DMLExecutionProvider` is removed from the list of available providers.
- Removing provider options from the configuration file results in the model defaulting to `CPUExecutionProvider`, leading to slower performance.
- The current setup does not fully utilize the NPU, which is present in modern devices like the Surface Pro 11. Supporting NPUs in ONNX Runtime GenAI would enable more efficient use of hardware and better performance.

**Comment by natke** [comment]
Thanks for raising these @ac1982. On the NPU support, the work is in progress.

For the conflicting execution providers, yes that is a current limitation. Please install the directml version of onnxruntime.

We also have work in progress to consolidate the execution providers.

I will close this issue for now, but please re-open or get back if you see further issues.

**Comment by rhenry74** [comment]
"Furthermore, there should be native support for NPUs in ONNX Runtime GenAI to fully leverage the capabilities of hardware like the Surface Pro 11, which comes with an NPU for AI acceleration. This would enable much faster inference on devices that include NPUs, rather than defaulting to just CPU or GPU." <- and free up the GPU to do graphics ;-)

AMD processors with a 4 in the third digit (like 7940HS) have NPUs. Millions of them are out in the wild.

https://www.tomshardware.com/tech-industry/artificial-intelligence/88-million-ai-capable-pcs-shipped-in-q2-2024

ONNX supports AMD NPU inference, so getting onnxruntime-genai running on them might not be that hard.

**Comment by axcpy08** [comment]
Could you please let us know when you expect to complete NPU support? I can't wait to see it!
