### ISSUE TITLE
phi 3 vision in winwows 11 cpu

### ISSUE THREAD

**Issue by balakreshnan** [microsoft/onnxruntime-genai#927]
**Describe the bug**
Traceback (most recent call last):
  File "C:\Code\gradioapps\mfgappsv1\phi3v.py", line 80, in <module>
    run(args)
  File "C:\Code\gradioapps\mfgappsv1\phi3v.py", line 51, in run
    inputs = processor(prompt, images=images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Number of unique image tags does not match the number of images.

**To Reproduce**
1. Go to https://onnxruntime.ai/docs/genai/tutorials/phi3-v.html#run-on-cpu
follow installation of genai and running the sample code in local laptop with python 3.12

**Expected behavior**

**Screenshots**
<img width="620" alt="image" src="https://github.com/user-attachments/assets/a6fa5126-512b-45e4-8b91-40fe6076f906">

**Comment by baijumeswani** [comment]
What version of `onnxruntime-genai` or `onnxruntime-genai-cuda` are you using?

Is the path provided `images` a valid image file. I would expect it to be image.png or image.jpeg. Could you please confirm that the input images is valid?

I just ran the example with `onnxruntime-genai-cuda` 0.4.0 and it ran well.

**Comment by balakreshnan** [comment]
Name: onnxruntime-genai
Version: 0.4.0
Summary: ONNX Runtime generate() API

**Comment by baijumeswani** [comment]
I was able to sync with @balakreshnan offline and the issue was that the path being provided was that of the folder containing the image. If you provide the path to the image, this issue went away.
