### ISSUE TITLE
Genny CUDA support does not work

### ISSUE THREAD

**Issue by lilhoser** [microsoft/onnxruntime-genai#933]
**Describe the bug**

Note: I'm using this model `https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx/tree/main/cuda/cuda-int4-rtn-block-32`

The readme for the Genny sample C# app states:

```
Debug_Cuda or Release_Cuda to launch the application with CUDA GPU support
```

However, when building with `Debug_Cuda`, I get the runtime error `CUDA execution provider is not enabled in this build.`

Genny app does specify a different nuget package in the `csproj`:

```
      <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" Version="0.4.0" />
      <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.4.0" Condition=" '$(Configuration)' == 'Debug_Cuda' OR '$(Configuration)' == 'Release_Cuda' " />
      <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.4.0" />
```

But in the console output, it's loading the wrong package:

```
'Genny.exe' (CoreCLR: clrhost): Loaded 'C:\tools\onnxruntime-genai\examples\csharp\Genny\Genny\bin\x64\Debug_Cuda\net8.0-windows7.0\Microsoft.ML.OnnxRuntimeGenAI.dll'. 
```

How is this supposed to work when all three `Microsoft.ML.OnnxRuntimeGenAI.dll` are referenced in the project?

**To Reproduce**
1. Clone genny repo
2. Build `Debug_Cuda` configuration
3. Load model `dir https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx/tree/main/cuda/cuda-int4-rtn-block-32`

**Expected behavior**

Expect the app to run with CUDA support and the right nuget package.

**Screenshots**
<img width="584" alt="image" src="https://github.com/user-attachments/assets/b8f56c15-b866-4704-a4d3-c95725b2060c">

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by lilhoser** [comment]
If I uninstall all but the CUDA nuget package and manually install CUDNN. it appears to work.

Is it not possible to have all packages included in the solution to build these different configurations?

**Comment by baijumeswani** [comment]
I think this should resolve the issue you were seeing: https://github.com/microsoft/onnxruntime-genai/pull/937.

Let me know if that worked for you.

**Comment by lilhoser** [comment]
Yep that works. Closing the ticket
