### ISSUE TITLE
linux path typos in onnxruntime-genai/examples/c/README.md

### ISSUE THREAD

**Issue by fwcore** [microsoft/onnxruntime-genai#944]
Thank you very much for providing us such a wonderful library to run GenAI via ONNX.

**Describe the bug**
I encountered a few Linux path typos in [`onnxruntime-genai/examples/c/README.md`](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/c/README.md), affecting the build and copy command. For example
<img width="626" alt="image" src="https://github.com/user-attachments/assets/5fb796b9-570a-4d5d-941d-b7e4d55007ec">

Please see my whole changes in https://github.com/fwcore/onnxruntime-genai/commit/489720527d8a240b3bc21f48ccb64dcddfbb9c8b

**To Reproduce**
1. During building `onnxruntime-genai/example/c` in Linux, run
```bash
python3 build.py --config Release --ort_home examples\c
```
The output will be
```
Traceback (most recent call last):
  File "/workspace/onnxruntime-genai/build.py", line 638, in <module>
    _validate_args(arguments)
  File "/workspace/onnxruntime-genai/build.py", line 340, in _validate_args
    raise ValueError(f"{args.ort_home} does not exist or is not a directory.")
ValueError: examplesc does not exist or is not a directory.
```

After fixing this, and run `cp build/Linux/release/onnxruntime-genai.so examples/c/lib`, one will get
```
cp: cannot stat 'build/Linux/release/onnxruntime-genai.so': No such file or directory
```

**Expected behavior**
The doc has correct linux path.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

If it's OK for you, I would like to send a PR for this. Thank you for your consideration.

**Comment by natke** [comment]
Yes please, do send a PR for this @fwcore. Thank you!
