### ISSUE TITLE
onnxruntime-genai use CPU or GPU for inference on Android？

### ISSUE THREAD

**Issue by lengjing606** [microsoft/onnxruntime-genai#961]
Does onnxruntime-genai use CPU or GPU for inference on Android？

**Comment by kunal-vaishnavi** [comment]
Currently, ONNX Runtime GenAI uses CPU for inference on Android. The work is in progress to support GPU on Android, and the next release will support NPU on Android via the QNN EP.

**Comment by lengjing606** [comment]
@kunal-vaishnavi Thanks for your reply
