### ISSUE TITLE
Error opening genai_config for running phi-3.5-mini-instruct-onnx (cuda-int4-awq-block-128) downloaded from hugging face

### ISSUE THREAD

**Issue by Vivihung** [microsoft/onnxruntime-genai#971]
**Describe the bug**
Got not useful error when trying to run phi-3.5-mini-instruct-onnx model locally on Windows.
```bash
RuntimeError: Error opening <path_to_downloaded_model>\cuda\cuda-int4-awq-block-128\phi-3.5-mini-instruct-cuda-int4-awq-block-128.onnx\genai_config.json
```

**To Reproduce**
1.  Install git large file system extension
```powershell
winget install -e --id GitHub.GitLFS
git lfs install
```
2. Install dependency
```python
pip install huggingface-hub[cli]
pip install onnxruntime-genai
pip install onnxruntime-genai-cuda
```
3. Download the model from HuggingFace
```powershell
huggingface-cli download microsoft/Phi-3.5-mini-instruct-onnx --include cuda/cuda-int4-awq-block-128/* --local-dir .
```
4. Install GPU driver and CUDA
    - [Install NVIDIA driver](https://www.nvidia.com/en-us/drivers/).
    - [Install CUDA](https://developer.nvidia.com/cuda-downloads) (3GB).
    - [Install cuDNN](https://developer.nvidia.com/cudnn-downloads) (524.3 MB) - For Win11, download the zip file and follow the instructions [here](https://github.com/microsoft/Phi-3CookBook/blob/main/md/08.Update/Phi35/041.ORTWindowGPUGuideline.md#5-set-nvidia-env) to 'install' the lib.

5. Run the model locally with ONNX Runtime GenAI API 
```python
import onnxruntime_genai

model = onnxruntime_genai.Model('<path_to_downloaded_model>\\cuda\\cuda-int4-awq-block-128\\phi-3.5-mini-instruct-cuda-int4-awq-block-128.onnx')

tokenizer = onnxruntime_genai.Tokenizer(model)
tokenizer_stream = tokenizer.create_stream()

search_options = {}
search_options['max_length'] = 2048

chat_template = '<|user|>\n{input} <|end|>\n<|assistant|>'

text = 'can you introduce yourself?'
prompt = f'{chat_template.format(input=text)}'

input_tokens = tokenizer.encode(prompt)

g_params = onnxruntime_genai.GeneratorParams(model)
params = onnxruntime_genai.GeneratorParams(model)

params.input_ids = input_tokens
params.set_search_options(**search_options)
generator = onnxruntime_genai.Generator(model, params)


while not generator.is_done():
    generator.compute_logits()
    generator.generate_next_token()

    new_token = generator.get_next_tokens()[0]
    print(tokenizer_stream.decode(new_token), end='', flush=True)
```

Error
```json
{
	"name": "RuntimeError",
	"message": "Error opening <path_to_downloaded_model>\\cuda\\cuda-int4-awq-block-128\\phi-3.5-mini-instruct-cuda-int4-awq-block-128.onnx\\genai_config.json",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 3
      1 import onnxruntime_genai
----> 3 model = onnxruntime_genai.Model('<path_to_downloaded_model>\\\\cuda\\\\cuda-int4-awq-block-128\\\\phi-3.5-mini-instruct-cuda-int4-awq-block-128.onnx')
      5 tokenizer = onnxruntime_genai.Tokenizer(model)
      6 tokenizer_stream = tokenizer.create_stream()

RuntimeError: Error opening <path_to_downloaded_model>\\cuda\\cuda-int4-awq-block-128\\phi-3.5-mini-instruct-cuda-int4-awq-block-128.onnx\\genai_config.json"
}
```

**Expected behavior**
1. The model is hosted without error
2. There is more information in the error message to help me resolve any issue.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - HW: NVIDIA RTX 2000 Ada GPU

**Comment by kunal-vaishnavi** [comment]
The path in `onnxruntime_genai.Model` should be the path to the folder containing the ONNX model. In your case, it should be as follows.

```python
import onnxruntime_genai

model = onnxruntime_genai.Model('<path_to_downloaded_model>\\cuda\\cuda-int4-awq-block-128\')
```

**Comment by Vivihung** [comment]
@kunal-vaishnavi - Thanks! Update the path makes the error gone but I got a new one. Thoughts?
```console
---------------------------------------------------------------------------
OrtException                              Traceback (most recent call last)
Cell In[3], [line 3](vscode-notebook-cell:?execution_count=3&line=3)
      [1](vscode-notebook-cell:?execution_count=3&line=1) import onnxruntime_genai
----> [3](vscode-notebook-cell:?execution_count=3&line=3) model = onnxruntime_genai.Model('<path_to_downloaded_model>\\cuda\\cuda-int4-awq-block-128\\')
      [5](vscode-notebook-cell:?execution_count=3&line=5) tokenizer = onnxruntime_genai.Tokenizer(model)
      [6](vscode-notebook-cell:?execution_count=3&line=6) tokenizer_stream = tokenizer.create_stream()

OrtException: CUDA execution provider is not enabled in this build.
```

Note:
I have CUDA_PATH in system variable and PATH includes both CUDA_PATH and the path to cuDNN bin folder.
```powershell
> $env:CUDA_PATH
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
```

```powershell
> $env:PATH
(Truncated version)
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\libnvvp;C:\Program Files\PowerShell\7\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Git LFS;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.3.2\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA\CUDNN\v9.5\bin;
```

**Comment by kunal-vaishnavi** [comment]
> Install dependency
> pip install huggingface-hub[cli]
> pip install onnxruntime-genai
> pip install onnxruntime-genai-cuda

For running with CUDA, only `onnxruntime-genai-cuda` is needed. All of the ONNX Runtime GenAI packages share the same namespace when importing so only one of them can be installed at once. Can you uninstall all ONNX Runtime GenAI packages and re-install only the one you need?

```bash
# Uninstall all ONNX Runtime GenAI packages
$ pip uninstall -y onnxruntime-genai onnxruntime-genai-cuda

# Install only the desired ONNX Runtime GenAI package
$ pip install onnxruntime-genai-cuda
```

**Comment by Vivihung** [comment]
@kunal-vaishnavi 
Thanks for the advice but we don't seem have luck here.  Still seeing the same error in jupyter notebook after 1) uninstall `onnxruntime-genai onnxruntime-genai-cuda`, 2) reinstall `onnxruntime-genai-cuda`, 3) restart kernel- 

`OrtException: CUDA execution provider is not enabled in this build.`

I also downgrade my CUDA version from 12.6 to 12.4 to avoid potential compatibility issues with PyTorch (The latest [PyTorch supporting matrix](https://pytorch.org/get-started/locally/) is with CUDA 12.4 on Windows). But the error remains...

Any other ideas? Is there a diagnostic command I could run to collect more debug trace?

![Image](https://github.com/user-attachments/assets/55d87298-2182-4b18-89d2-37d2fcdf8d33)

**Comment by baijumeswani** [comment]
It seems like the version of `onnxruntime` python package is not the GPU one. Please run

```
pip uninstall onnxruntime onnxruntime-gpu -y
pip install onnxruntime-gpu
```

**Comment by Vivihung** [comment]
Awesome! @baijumeswani - you found the issue!!
After uninstalling `onnxruntime onnxruntime-gpu` and install `onnxruntime-gpu`, I finally got the phi model running locally with ORT GenAI and my GPU. Thank you, @baijumeswani and @kunal-vaishnavi !

Btw, I do think the tool can benefit from the following improvements:
1. [The document](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi-3-tutorial.md) should have a section to mention the available quantization params. Or provide a way to list the quantization versions of a ONNX GenAI model.
Users might not know what type of quantization model is available and blindly copy the parameters from phi-3 example. I'm not a super user of huggingface-cli, if there is a way to list out the quantization versions of a given ONNX model, that will be helpful.
```bash
# This will fail.
huggingface-cli download microsoft/Phi-3.5-mini-instruct-onnx --include cuda/cuda-int4-rtn-block-32/* --local-dir .

# This will work.
huggingface-cli download microsoft/Phi-3.5-mini-instruct-onnx --include cuda/cuda-int4-awq-block-128/* --local-dir .
```

2. Clear instructions in the [ORT GenAI API example](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi-3-tutorial.md) to remind users using ORT-GPU pkg not ORT.
This is my personal experience as a reference: As a new user who focus on running a SLM with ORT GenAI API, I rely on the example to tell me everything I need to know. However, I missed the critical part to install the right ORT GPU pkg. I would assume others might hit similar issue/confusion.

3. Improve the error message of `OrtException: CUDA execution provider is not enabled in this build.`
This error message isn't actionable and doesn't provide sufficient information to help user/dev self-resolving the issue.

**Comment by Vivihung** [comment]
For others who might hit the same error, this is the final dependencies I installed
```python
pip install huggingface-hub[cli]

pip uninstall onnxruntime onnxruntime-gpu -y
pip uninstall onnxruntime-genai onnxruntime-genai-cuda -y

pip install onnxruntime-gpu
pip install onnxruntime-genai-cuda
```
