### ISSUE TITLE
Model load failure in Onnxruntime-genai directml when onnxruntime is also installed in the same environment

### ISSUE THREAD

**Issue by ramkrishna2910** [microsoft/onnxruntime-genai#983]
**Describe the bug**
Model load failure in Onnxruntime-genai when onnxruntime is also installed in the same environment

**To Reproduce**
- Create a test env 1
- pip install onnxruntime-directml onnxruntime-genai-directml
```
>>> import onnxruntime_genai as og
>>> input_folder=r"C:\Users\ramkr\work\turnkeyml\src\turnkeyml\llm\tools\ort_genai\models\phi-3-mini-4k-instruct\directml\directml-int4-awq-block-128"
>>> model = og.Model(input_folder)
```
The model will load successfully

- Create a test env 2
- pip install onnxruntime-directml onnxruntime-genai-directml onnxruntime
```
>>> import onnxruntime_genai as og
>>> input_folder=r"C:\Users\ramkr\work\turnkeyml\src\turnkeyml\llm\tools\ort_genai\models\phi-3-mini-4k-instruct\directml\directml-int4-awq-block-128"
>>> model = og.Model(input_folder)
```
The model load will fail with the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
onnxruntime_genai.onnxruntime_genai.OrtException: Specified provider is not supported.
```

**Expected behavior**
Model load expected to pass irrespective of onnxruntime 

**Screenshots**
Failure with Onnxruntime in env:
![Image](https://github.com/user-attachments/assets/be79b3cc-f5fc-4d11-b37e-9b9807603dac)

Success without onnxruntime in env:
![Image](https://github.com/user-attachments/assets/a7b6d5f2-0e6a-4060-a5ed-c1540e6bb109)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
This could be related to #982 

@natke @kunal-vaishnavi @hisham-hchowdhu

**Comment by natke** [comment]
Hi @ramkrishna2910, this is likely because you have 2 versions of onnxruntime installed: onnxruntime-directml and onnxruntime. If you remove onnxruntime, you should be good.

**Comment by hisham-hchowdhu** [comment]
onnxruntime by default doesn't have the dml ep enabled i believe. so remove it as Nate mentioned and use onnxruntime-dml

**Comment by ramkrishna2910** [comment]
@kunal-vaishnavi @natke  what about tools that need onnxruntime and onnxruntime-directml installed in the same env.
Packages should be able to co-exist right?

**Comment by kunal-vaishnavi** [comment]
Both packages cannot be installed in the same environment because they both use the same location when installing (i.e. both packages are installed at `/path/to/site-packages/onnxruntime/` ) and when importing (i.e. both packages use the same `import onnxruntime as ort` step).
