### ISSUE TITLE
`onnxruntime_genai.models.builder` script produces model with incorrect tokenizer schema

### ISSUE THREAD

**Issue by cecheta** [microsoft/onnxruntime-genai#991]
**Describe the bug**
When using the `onnxruntime_genai.models.builder` script to generate an ONNX model from a model on Hugging Face, I cannot run the model, as the tokenizer is invalid JSON.

**To Reproduce**
Example using `microsoft/Phi-3-mini-4k-instruct`

1. Install dependencies

```bash
pip install numpy
pip install --pre onnxruntime-genai
pip install torch transformers onnx "huggingface_hub[cli]"
```

2. Log in to Hugging Face

```bash
huggingface-cli login
```

3. Convert `microsoft/Phi-3-mini-4k-instruct` to ONNX

```bash
python -m onnxruntime_genai.models.builder -m microsoft/Phi-3-mini-4k-instruct -o phi3 -p int4 -e cpu
```

4. Run ONNX model using `onnxruntime_genai`

```bash
curl https://raw.githubusercontent.com/microsoft/onnxruntime-genai/main/examples/python/phi3-qa.py -o phi3-qa.py
python phi3-qa.py -m phi3
```

5. Error

```
Traceback (most recent call last):
  File "/home/azureuser/phi3-qa.py", line 93, in <module>
    main(args)
  File "/home/azureuser/phi3-qa.py", line 13, in main
    tokenizer = og.Tokenizer(model)
RuntimeError: [json.exception.type_error.302] type must be string, but is array
```

**Expected behavior**
The `phi3-qa.py` script should start without any errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS - Standard_NV12s_v3 

**Additional context**
Comparing `tokenizer.json` in the generated ONNX model against `tokenizer.json` present in the `microsoft/Phi-3-mini-4k-instruct-onnx` model on Hugging Face, it appears that the difference lies in `.model.merges`, where it is a list of list of strings, rather than a list of strings.

**Comment by kunal-vaishnavi** [comment]
This is a known issue from Hugging Face's `transformers` package. Suggested workarounds are listed [here](https://github.com/microsoft/onnxruntime-genai/issues/957) and in the [troubleshooting section](https://onnxruntime.ai/docs/genai/howto/troubleshoot.html#transformers--tokenizers-incompatibility-with-onnx-runtime-generate).

**Comment by cecheta** [comment]
Thanks a lot. happy to close
